+ oIFS=' 	
'
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --configs=reports/10.10.10.10
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ configs =~ ^(configs|c)$ ]]
+ export configs_dirpath=reports/10.10.10.10
+ configs_dirpath=reports/10.10.10.10
+ [[ configs =~ ^(index|n)$ ]]
+ [[ configs =~ ^(ip-addr|i)$ ]]
+ [[ configs =~ ^(logger|l)$ ]]
+ [[ configs =~ ^(matrix|m)$ ]]
+ [[ configs =~ ^(reports|r)$ ]]
+ [[ configs =~ ^(classify|g)$ ]]
+ [[ configs =~ ^(validate|v)$ ]]
+ [[ configs == \d\e\b\u\g ]]
+ [[ configs == \d\r\y\-\r\u\n ]]
+ [[ configs == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --index=04
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ index =~ ^(configs|c)$ ]]
+ [[ index =~ ^(index|n)$ ]]
+ local target_index=04
+ [[ index =~ ^(ip-addr|i)$ ]]
+ [[ index =~ ^(logger|l)$ ]]
+ [[ index =~ ^(matrix|m)$ ]]
+ [[ index =~ ^(reports|r)$ ]]
+ [[ index =~ ^(classify|g)$ ]]
+ [[ index =~ ^(validate|v)$ ]]
+ [[ index == \d\e\b\u\g ]]
+ [[ index == \d\r\y\-\r\u\n ]]
+ [[ index == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --ip-addr=10.10.10.10
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ ip-addr =~ ^(configs|c)$ ]]
+ [[ ip-addr =~ ^(index|n)$ ]]
+ [[ ip-addr =~ ^(ip-addr|i)$ ]]
+ local target_address=10.10.10.10
+ [[ ip-addr =~ ^(logger|l)$ ]]
+ [[ ip-addr =~ ^(matrix|m)$ ]]
+ [[ ip-addr =~ ^(reports|r)$ ]]
+ [[ ip-addr =~ ^(classify|g)$ ]]
+ [[ ip-addr =~ ^(validate|v)$ ]]
+ [[ ip-addr == \d\e\b\u\g ]]
+ [[ ip-addr == \d\r\y\-\r\u\n ]]
+ [[ ip-addr == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/configs-parser--10.10.10.10.console
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ logger =~ ^(configs|c)$ ]]
+ [[ logger =~ ^(index|n)$ ]]
+ [[ logger =~ ^(ip-addr|i)$ ]]
+ [[ logger =~ ^(logger|l)$ ]]
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/configs-parser--10.10.10.10.console
+ [[ logger =~ ^(matrix|m)$ ]]
+ [[ logger =~ ^(reports|r)$ ]]
+ [[ logger =~ ^(classify|g)$ ]]
+ [[ logger =~ ^(validate|v)$ ]]
+ [[ logger == \d\e\b\u\g ]]
+ [[ logger == \d\r\y\-\r\u\n ]]
+ [[ logger == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --matrix=matrix.json
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ matrix =~ ^(configs|c)$ ]]
+ [[ matrix =~ ^(index|n)$ ]]
+ [[ matrix =~ ^(ip-addr|i)$ ]]
+ [[ matrix =~ ^(logger|l)$ ]]
+ [[ matrix =~ ^(matrix|m)$ ]]
+ local matrix_filename=matrix.json
+ [[ matrix =~ ^(reports|r)$ ]]
+ [[ matrix =~ ^(classify|g)$ ]]
+ [[ matrix =~ ^(validate|v)$ ]]
+ [[ matrix == \d\e\b\u\g ]]
+ [[ matrix == \d\r\y\-\r\u\n ]]
+ [[ matrix == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --reports=reports
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ reports =~ ^(configs|c)$ ]]
+ [[ reports =~ ^(index|n)$ ]]
+ [[ reports =~ ^(ip-addr|i)$ ]]
+ [[ reports =~ ^(logger|l)$ ]]
+ [[ reports =~ ^(matrix|m)$ ]]
+ [[ reports =~ ^(reports|r)$ ]]
+ local reports_location=reports
+ [[ reports =~ ^(classify|g)$ ]]
+ [[ reports =~ ^(validate|v)$ ]]
+ [[ reports == \d\e\b\u\g ]]
+ [[ reports == \d\r\y\-\r\u\n ]]
+ [[ reports == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --classify
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ classify =~ ^(configs|c)$ ]]
+ [[ classify =~ ^(index|n)$ ]]
+ [[ classify =~ ^(ip-addr|i)$ ]]
+ [[ classify =~ ^(logger|l)$ ]]
+ [[ classify =~ ^(matrix|m)$ ]]
+ [[ classify =~ ^(reports|r)$ ]]
+ [[ classify =~ ^(classify|g)$ ]]
+ export classify_targets=true
+ classify_targets=true
+ [[ classify =~ ^(validate|v)$ ]]
+ [[ classify == \d\e\b\u\g ]]
+ [[ classify == \d\r\y\-\r\u\n ]]
+ [[ classify == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --verbose
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ verbose =~ ^(configs|c)$ ]]
+ [[ verbose =~ ^(index|n)$ ]]
+ [[ verbose =~ ^(ip-addr|i)$ ]]
+ [[ verbose =~ ^(logger|l)$ ]]
+ [[ verbose =~ ^(matrix|m)$ ]]
+ [[ verbose =~ ^(reports|r)$ ]]
+ [[ verbose =~ ^(classify|g)$ ]]
+ [[ verbose =~ ^(validate|v)$ ]]
+ [[ verbose == \d\e\b\u\g ]]
+ [[ verbose == \d\r\y\-\r\u\n ]]
+ [[ verbose == \v\e\r\b\o\s\e ]]
+ export verbose=true
+ verbose=true
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --debug
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ debug =~ ^(configs|c)$ ]]
+ [[ debug =~ ^(index|n)$ ]]
+ [[ debug =~ ^(ip-addr|i)$ ]]
+ [[ debug =~ ^(logger|l)$ ]]
+ [[ debug =~ ^(matrix|m)$ ]]
+ [[ debug =~ ^(reports|r)$ ]]
+ [[ debug =~ ^(classify|g)$ ]]
+ [[ debug =~ ^(validate|v)$ ]]
+ [[ debug == \d\e\b\u\g ]]
+ export debug=true
+ debug=true
+ [[ debug == \d\r\y\-\r\u\n ]]
+ [[ debug == \v\e\r\b\o\s\e ]]
+ IFS=' 	
'
+ [[ -z true ]]
+ [[ -z false ]]
+ [[ -z true ]]
+ [[ -z /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/configs-parser--10.10.10.10.console ]]
+ local configs_extract__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/configs-extract.log
+ :
+ [[ -z matrix.json ]]
+ [[ ! -f matrix.json ]]
+ [[ -z true ]]
+ [[ true == true ]]
+ [[ ! -f matrix.json ]]
+ jq -e 'length > 0' matrix.json
++ cat matrix.json
+ export 'matrix_configs=[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ matrix_configs='[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ export configs_dirpath=reports/10.10.10.10
+ configs_dirpath=reports/10.10.10.10
+ export reports_location=reports
+ reports_location=reports
+ [[ -z 04 ]]
+ [[ -z false ]]
+ local target_configlist_json=targets/10.10.10.10.json
+ [[ ! -f targets/10.10.10.10.json ]]
+ [[ true == true ]]
+ message 'Loading target config list from: targets/10.10.10.10.json'
+ [[ -n Loading target config list from: targets/10.10.10.10.json ]]
+ local 'message=Loading target config list from: targets/10.10.10.10.json'
+ echo -e 'Loading target config list from: targets/10.10.10.10.json'
Loading target config list from: targets/10.10.10.10.json
+ source_configs=()
+ declare -ga source_configs
+ mapfile -t source_configs
++ jq -r --arg reports reports '
        .target as $ip
        | .locations
        | to_entries[]
        | .key as $site
        | .value.devices[]
        | "\($reports)/\($ip)/\($site)/\(.config.object)"
      ' targets/10.10.10.10.json
+ [[ true == true ]]
+ message 'Found 6 configurations:'
+ [[ -n Found 6 configurations: ]]
+ local 'message=Found 6 configurations:'
+ echo -e 'Found 6 configurations:'
Found 6 configurations:
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for config in "${source_configs[@]}"
+ message '  - reports/10.10.10.10/cisco/.objects/access-sw1-west.list'
+ [[ -n   - reports/10.10.10.10/cisco/.objects/access-sw1-west.list ]]
+ local 'message=  - reports/10.10.10.10/cisco/.objects/access-sw1-west.list'
+ echo -e '  - reports/10.10.10.10/cisco/.objects/access-sw1-west.list'
  - reports/10.10.10.10/cisco/.objects/access-sw1-west.list
+ for config in "${source_configs[@]}"
+ message '  - reports/10.10.10.10/cisco/.objects/campus-sw-access01.list'
+ [[ -n   - reports/10.10.10.10/cisco/.objects/campus-sw-access01.list ]]
+ local 'message=  - reports/10.10.10.10/cisco/.objects/campus-sw-access01.list'
+ echo -e '  - reports/10.10.10.10/cisco/.objects/campus-sw-access01.list'
  - reports/10.10.10.10/cisco/.objects/campus-sw-access01.list
+ for config in "${source_configs[@]}"
+ message '  - reports/10.10.10.10/cisco/.objects/dmz-fw2-backup.list'
+ [[ -n   - reports/10.10.10.10/cisco/.objects/dmz-fw2-backup.list ]]
+ local 'message=  - reports/10.10.10.10/cisco/.objects/dmz-fw2-backup.list'
+ echo -e '  - reports/10.10.10.10/cisco/.objects/dmz-fw2-backup.list'
  - reports/10.10.10.10/cisco/.objects/dmz-fw2-backup.list
+ for config in "${source_configs[@]}"
+ message '  - reports/10.10.10.10/fortinet/.objects/fg-campus-core.list'
+ [[ -n   - reports/10.10.10.10/fortinet/.objects/fg-campus-core.list ]]
+ local 'message=  - reports/10.10.10.10/fortinet/.objects/fg-campus-core.list'
+ echo -e '  - reports/10.10.10.10/fortinet/.objects/fg-campus-core.list'
  - reports/10.10.10.10/fortinet/.objects/fg-campus-core.list
+ for config in "${source_configs[@]}"
+ message '  - reports/10.10.10.10/fortinet/.objects/fg-testing-config.list'
+ [[ -n   - reports/10.10.10.10/fortinet/.objects/fg-testing-config.list ]]
+ local 'message=  - reports/10.10.10.10/fortinet/.objects/fg-testing-config.list'
+ echo -e '  - reports/10.10.10.10/fortinet/.objects/fg-testing-config.list'
  - reports/10.10.10.10/fortinet/.objects/fg-testing-config.list
+ for config in "${source_configs[@]}"
+ message '  - reports/10.10.10.10/misc/.objects/fw3.list'
+ [[ -n   - reports/10.10.10.10/misc/.objects/fw3.list ]]
+ local 'message=  - reports/10.10.10.10/misc/.objects/fw3.list'
+ echo -e '  - reports/10.10.10.10/misc/.objects/fw3.list'
  - reports/10.10.10.10/misc/.objects/fw3.list
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ [[ -z 10.10.10.10 ]]
++ print 10.10.10.10
++ [[ -n 10.10.10.10 ]]
++ echo -en 10.10.10.10
++ sed -E 's/[[:space:]]+//g'
++ tr -d '\r'
+ target_address=10.10.10.10
+ [[ false == true ]]
+ extract_jobs_pid=()
+ declare -ga extract_jobs_pid
+ extract_jobs2files_mapping=()
+ declare -gA extract_jobs2files_mapping
+ extract_jobs2console_mapping=()
+ declare -gA extract_jobs2console_mapping
+ local configs_extract__script=configs-extract
+ local object_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json
++ dirname /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json
+ mkdir -p /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10
+ for config_filename in "${source_configs[@]}"
++ basename reports/10.10.10.10/cisco/.objects/access-sw1-west.list
+ local cfg_basename=access-sw1-west.list
+ local object_fragments_per_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json
+ local extract_location=jobs/configs-extract/10.10.10.10
+ mkdir -p jobs/configs-extract/10.10.10.10
+ local logging_filename=access-sw1-west
+ local configs_extract__console=console/configs-extract.console
+ local configs_extract__logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/access-sw1-west
+ local job_pid=27398
+ extract_jobs_pid+=("${job_pid}")
+ extract_jobs2files_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json
+ extract_jobs2console_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/access-sw1-west
+ for config_filename in "${source_configs[@]}"
+ configs_extract --config=reports/10.10.10.10/cisco/.objects/access-sw1-west.list --search=10.10.10.10 --listing=targets/10.10.10.10.json --output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json --logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/access-sw1-west.console
++ basename reports/10.10.10.10/cisco/.objects/campus-sw-access01.list
+ local cfg_basename=campus-sw-access01.list
+ local object_fragments_per_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json
+ local extract_location=jobs/configs-extract/10.10.10.10
+ mkdir -p jobs/configs-extract/10.10.10.10
+ local logging_filename=campus-sw-access01
+ local configs_extract__console=console/configs-extract.console
+ local configs_extract__logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/campus-sw-access01
+ local job_pid=27462
+ extract_jobs_pid+=("${job_pid}")
+ extract_jobs2files_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json
+ extract_jobs2console_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/campus-sw-access01
+ for config_filename in "${source_configs[@]}"
+ configs_extract --config=reports/10.10.10.10/cisco/.objects/campus-sw-access01.list --search=10.10.10.10 --listing=targets/10.10.10.10.json --output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json --logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/campus-sw-access01.console
++ basename reports/10.10.10.10/cisco/.objects/dmz-fw2-backup.list
+ local cfg_basename=dmz-fw2-backup.list
+ local object_fragments_per_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json
+ local extract_location=jobs/configs-extract/10.10.10.10
+ mkdir -p jobs/configs-extract/10.10.10.10
+ local logging_filename=dmz-fw2-backup
+ local configs_extract__console=console/configs-extract.console
+ local configs_extract__logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/dmz-fw2-backup
+ local job_pid=27539
+ extract_jobs_pid+=("${job_pid}")
+ extract_jobs2files_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json
+ extract_jobs2console_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/dmz-fw2-backup
+ for config_filename in "${source_configs[@]}"
+ configs_extract --config=reports/10.10.10.10/cisco/.objects/dmz-fw2-backup.list --search=10.10.10.10 --listing=targets/10.10.10.10.json --output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json --logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/dmz-fw2-backup.console
++ basename reports/10.10.10.10/fortinet/.objects/fg-campus-core.list
+ local cfg_basename=fg-campus-core.list
+ local object_fragments_per_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json
+ local extract_location=jobs/configs-extract/10.10.10.10
+ mkdir -p jobs/configs-extract/10.10.10.10
+ local logging_filename=fg-campus-core
+ local configs_extract__console=console/configs-extract.console
+ local configs_extract__logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/fg-campus-core
+ local job_pid=27637
+ extract_jobs_pid+=("${job_pid}")
+ extract_jobs2files_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json
+ extract_jobs2console_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/fg-campus-core
+ for config_filename in "${source_configs[@]}"
+ configs_extract --config=reports/10.10.10.10/fortinet/.objects/fg-campus-core.list --search=10.10.10.10 --listing=targets/10.10.10.10.json --output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json --logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/fg-campus-core.console
++ basename reports/10.10.10.10/fortinet/.objects/fg-testing-config.list
+ local cfg_basename=fg-testing-config.list
+ local object_fragments_per_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json
+ local extract_location=jobs/configs-extract/10.10.10.10
+ mkdir -p jobs/configs-extract/10.10.10.10
+ local logging_filename=fg-testing-config
+ local configs_extract__console=console/configs-extract.console
+ local configs_extract__logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/fg-testing-config
+ local job_pid=27726
+ extract_jobs_pid+=("${job_pid}")
+ extract_jobs2files_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json
+ extract_jobs2console_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/fg-testing-config
+ for config_filename in "${source_configs[@]}"
+ configs_extract --config=reports/10.10.10.10/fortinet/.objects/fg-testing-config.list --search=10.10.10.10 --listing=targets/10.10.10.10.json --output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json --logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/fg-testing-config.console
++ basename reports/10.10.10.10/misc/.objects/fw3.list
+ local cfg_basename=fw3.list
+ local object_fragments_per_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json
+ local extract_location=jobs/configs-extract/10.10.10.10
+ mkdir -p jobs/configs-extract/10.10.10.10
+ local logging_filename=fw3
+ local configs_extract__console=console/configs-extract.console
+ local configs_extract__logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/fw3
+ local job_pid=27813
+ extract_jobs_pid+=("${job_pid}")
+ extract_jobs2files_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json
+ extract_jobs2console_mapping["${target_address}::${job_pid}"]=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/fw3
+ ((  6 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27462
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ configs_extract --config=reports/10.10.10.10/misc/.objects/fw3.list --search=10.10.10.10 --listing=targets/10.10.10.10.json --output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json --logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/fw3.console
+ ((  6 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27462
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  6 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27462
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  6 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27462
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  6 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27462
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  6 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27462
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  6 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27462
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  6 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27462
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  6 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27462
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27813 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\4\6\2 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27398 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\4\6\2 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27539 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\4\6\2 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27637 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\4\6\2 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27726 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\4\6\2 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27462 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\4\6\2 ]]
+ logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json
+ break
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  5 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  5 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  5 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27398
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27813 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\3\9\8 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27398 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\3\9\8 ]]
+ logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json
+ break
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27726
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27813 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\7\2\6 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27398 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\7\2\6 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27539 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\7\2\6 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27637 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\7\2\6 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27726 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\7\2\6 ]]
+ logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json
+ break
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ valid_extract_jobs_pid+=("${pid}")
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  3 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ valid_extract_jobs_pid+=("${pid}")
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27637
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27813 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\6\3\7 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27398 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\6\3\7 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27539 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\6\3\7 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27637 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\6\3\7 ]]
+ logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json
+ break
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27813
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27813 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\8\1\3 ]]
+ logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json
+ break
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  1 > 0  ))
+ valid_extract_jobs_pid=()
+ local valid_extract_jobs_pid
+ for pid in "${extract_jobs_pid[@]}"
+ kill -0 27539
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27813 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\5\3\9 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27398 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\5\3\9 ]]
+ continue
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27539 == \1\0\.\1\0\.\1\0\.\1\0\:\:\2\7\5\3\9 ]]
+ logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json
+ break
+ extract_jobs_pid=("${valid_extract_jobs_pid[@]}")
+ sleep 0.1
+ ((  0 > 0  ))
+ :
+ message '>>> Listing Jobs->Files (extract_jobs2files_mapping): '
+ [[ -n >>> Listing Jobs->Files (extract_jobs2files_mapping):  ]]
+ local 'message=>>> Listing Jobs->Files (extract_jobs2files_mapping): '
+ echo -e '>>> Listing Jobs->Files (extract_jobs2files_mapping): '
>>> Listing Jobs->Files (extract_jobs2files_mapping): 
+ for key in "${!extract_jobs2files_mapping[@]}"
+ echo '10.10.10.10::27813 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json'
10.10.10.10::27813 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ echo '10.10.10.10::27398 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json'
10.10.10.10::27398 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ echo '10.10.10.10::27539 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json'
10.10.10.10::27539 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ echo '10.10.10.10::27637 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json'
10.10.10.10::27637 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ echo '10.10.10.10::27726 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json'
10.10.10.10::27726 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ echo '10.10.10.10::27462 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json'
10.10.10.10::27462 = /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27813 == \1\0\.\1\0\.\1\0\.\1\0\:\:* ]]
+ fragment=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json
+ ls -al /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json
-rw-r--r--  1 emvaldes  staff  3150 Jun  9 22:55 /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json
+ cat -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json
     1	{
     2	  "site": "misc",
     3	  "specs": {
     4	    "vendor": "cisco",
     5	    "model": "",
     6	    "version": "",
     7	    "domain": "",
     8	    "hostname": ""
     9	  },
    10	  "device": "fw3",
    11	  "objects": [
    12	    {
    13	      "object": "object-group",
    14	      "type": "network",
    15	      "partner": "Panther-Edge",
    16	      "description": "Internet-facing proxy systems",
    17	      "items": [
    18	        "network-object host 172.16.0.5"
    19	      ],
    20	      "others": [
    21	        "network-object host 203.0.113.25"
    22	      ],
    23	      "group": "Unclassified"
    24	    },
    25	    {
    26	      "object": "object-group",
    27	      "type": "network",
    28	      "partner": "Wakanda-Core",
    29	      "description": "National Core Routing Zone",
    30	      "items": [
    31	        "network-object host 10.0.2.3"
    32	      ],
    33	      "others": [
    34	        "network-object host 192.168.1.10",
    35	        "network-object 10.0.0.0 255.255.255.0"
    36	      ],
    37	      "group": "Unclassified"
    38	    },
    39	    {
    40	      "object": "object-group",
    41	      "type": "network",
    42	      "partner": "Shield-WiFi",
    43	      "description": "Shield-controlled wireless network",
    44	      "items": [
    45	        "network-object host 10.10.10.10"
    46	      ],
    47	      "others": [
    48	        "network-object 192.168.100.0 255.255.255.0"
    49	      ],
    50	      "group": "Unclassified"
    51	    }
    52	  ]
    53	}
    54	{
    55	  "site": "misc",
    56	  "specs": {
    57	    "vendor": "cisco",
    58	    "model": "",
    59	    "version": "",
    60	    "domain": "",
    61	    "hostname": ""
    62	  },
    63	  "device": "fw3",
    64	  "objects": [
    65	    {
    66	      "object": "object-group",
    67	      "type": "network",
    68	      "partner": "Panther-Edge",
    69	      "description": "Internet-facing proxy systems",
    70	      "items": [
    71	        "network-object host 172.16.0.5"
    72	      ],
    73	      "others": [
    74	        "network-object host 203.0.113.25"
    75	      ],
    76	      "group": "Unclassified"
    77	    },
    78	    {
    79	      "object": "object-group",
    80	      "type": "network",
    81	      "partner": "Wakanda-Core",
    82	      "description": "National Core Routing Zone",
    83	      "items": [
    84	        "network-object host 10.0.2.3"
    85	      ],
    86	      "others": [
    87	        "network-object host 192.168.1.10",
    88	        "network-object 10.0.0.0 255.255.255.0"
    89	      ],
    90	      "group": "Unclassified"
    91	    },
    92	    {
    93	      "object": "object-group",
    94	      "type": "network",
    95	      "partner": "Shield-WiFi",
    96	      "description": "Shield-controlled wireless network",
    97	      "items": [
    98	        "network-object host 10.10.10.10"
    99	      ],
   100	      "others": [
   101	        "network-object 192.168.100.0 255.255.255.0"
   102	      ],
   103	      "group": "Unclassified"
   104	    },
   105	    {
   106	      "object": "object",
   107	      "type": "network",
   108	      "partner": "Edge-Terminal",
   109	      "description": "Internet firewall handoff",
   110	      "items": [
   111	        "host 172.16.0.5"
   112	      ],
   113	      "others": [],
   114	      "group": "Unclassified"
   115	    },
   116	    {
   117	      "object": "object",
   118	      "type": "network",
   119	      "partner": "Panther-Gateway",
   120	      "description": "Secure outbound concentrator",
   121	      "items": [
   122	        "host 10.0.2.3"
   123	      ],
   124	      "others": [],
   125	      "group": "Unclassified"
   126	    },
   127	    {
   128	      "object": "object",
   129	      "type": "network",
   130	      "partner": "Shield-WiFi-Alias",
   131	      "description": "Guest NAT",
   132	      "items": [
   133	        "host 10.10.10.10"
   134	      ],
   135	      "others": [],
   136	      "group": "Unclassified"
   137	    }
   138	  ]
   139	}
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json ]]
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fw3.list--14102.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27398 == \1\0\.\1\0\.\1\0\.\1\0\:\:* ]]
+ fragment=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json
+ ls -al /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json
-rw-r--r--  1 emvaldes  staff  1927 Jun  9 22:55 /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json
+ cat -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json
     1	{
     2	  "site": "cisco",
     3	  "specs": {
     4	    "vendor": "cisco",
     5	    "model": "",
     6	    "version": "12.4",
     7	    "domain": "",
     8	    "hostname": "access-sw1-west"
     9	  },
    10	  "device": "access-sw1-west",
    11	  "objects": [
    12	    {
    13	      "object": "object-group",
    14	      "type": "network",
    15	      "partner": "MGMT-ACCESS",
    16	      "description": "Management objects",
    17	      "items": [
    18	        "network-object host 10.10.10.10"
    19	      ],
    20	      "others": [
    21	        "network-object host 192.168.0.1",
    22	        "network-object host 192.168.0.100"
    23	      ],
    24	      "group": "Unclassified"
    25	    },
    26	    {
    27	      "object": "interface",
    28	      "type": "Vlan1",
    29	      "partner": false,
    30	      "description": "Management Interface",
    31	      "items": [
    32	        "ip address 192.168.0.1 255.255.255.0"
    33	      ],
    34	      "others": [],
    35	      "group": "Business-Unit-Networks"
    36	    }
    37	  ]
    38	}
    39	{
    40	  "site": "cisco",
    41	  "specs": {
    42	    "vendor": "cisco",
    43	    "model": "",
    44	    "version": "12.4",
    45	    "domain": "",
    46	    "hostname": "access-sw1-west"
    47	  },
    48	  "device": "access-sw1-west",
    49	  "objects": [
    50	    {
    51	      "object": "object-group",
    52	      "type": "network",
    53	      "partner": "MGMT-ACCESS",
    54	      "description": "Management objects",
    55	      "items": [
    56	        "network-object host 10.10.10.10"
    57	      ],
    58	      "others": [
    59	        "network-object host 192.168.0.1",
    60	        "network-object host 192.168.0.100"
    61	      ],
    62	      "group": "Unclassified"
    63	    },
    64	    {
    65	      "object": "interface",
    66	      "type": "Vlan1",
    67	      "partner": false,
    68	      "description": "Management Interface",
    69	      "items": [
    70	        "ip address 192.168.0.1 255.255.255.0"
    71	      ],
    72	      "others": [],
    73	      "group": "Business-Unit-Networks"
    74	    },
    75	    {
    76	      "object": "object-group",
    77	      "type": "network",
    78	      "partner": "Mutant-WiFi",
    79	      "description": "Controlled guest devices",
    80	      "items": [
    81	        "network-object host 10.10.10.10"
    82	      ],
    83	      "others": [],
    84	      "group": "Unclassified"
    85	    }
    86	  ]
    87	}
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json ]]
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--access-sw1-west.list--24812.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27539 == \1\0\.\1\0\.\1\0\.\1\0\:\:* ]]
+ fragment=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json
+ ls -al /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json
-rw-r--r--  1 emvaldes  staff  3195 Jun  9 22:55 /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json
+ cat -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json
     1	{
     2	  "site": "cisco",
     3	  "specs": {
     4	    "vendor": "cisco",
     5	    "model": "ASA",
     6	    "version": "9.12(4)",
     7	    "domain": "global.dmz.example.net",
     8	    "hostname": "dmz-fw2-backup"
     9	  },
    10	  "device": "dmz-fw2-backup",
    11	  "objects": [
    12	    {
    13	      "object": "object-group",
    14	      "type": "network",
    15	      "partner": "Watchtower-DMZ",
    16	      "description": "Global secure relay",
    17	      "items": [
    18	        "network-object host 192.0.2.50"
    19	      ],
    20	      "others": [],
    21	      "group": "Unclassified"
    22	    },
    23	    {
    24	      "object": "interface",
    25	      "type": "GigabitEthernet0/0",
    26	      "partner": false,
    27	      "description": "Guest access interface",
    28	      "items": [
    29	        "ip address 10.10.10.10 255.255.255.0"
    30	      ],
    31	      "others": [
    32	        "nameif guest"
    33	      ],
    34	      "group": "Unclassified"
    35	    }
    36	  ]
    37	}
    38	{
    39	  "site": "cisco",
    40	  "specs": {
    41	    "vendor": "cisco",
    42	    "model": "ASA",
    43	    "version": "9.12(4)",
    44	    "domain": "global.dmz.example.net",
    45	    "hostname": "dmz-fw2-backup"
    46	  },
    47	  "device": "dmz-fw2-backup",
    48	  "objects": [
    49	    {
    50	      "object": "object-group",
    51	      "type": "network",
    52	      "partner": "Watchtower-DMZ",
    53	      "description": "Global secure relay",
    54	      "items": [
    55	        "network-object host 192.0.2.50"
    56	      ],
    57	      "others": [],
    58	      "group": "Unclassified"
    59	    },
    60	    {
    61	      "object": "interface",
    62	      "type": "GigabitEthernet0/0",
    63	      "partner": false,
    64	      "description": "Guest access interface",
    65	      "items": [
    66	        "ip address 10.10.10.10 255.255.255.0"
    67	      ],
    68	      "others": [
    69	        "nameif guest"
    70	      ],
    71	      "group": "Unclassified"
    72	    },
    73	    {
    74	      "object": "object",
    75	      "type": "network",
    76	      "partner": "Shield-WiFi-Alias",
    77	      "description": "Guest NAT",
    78	      "items": [
    79	        "host 10.10.10.10"
    80	      ],
    81	      "others": [],
    82	      "group": "Unclassified"
    83	    }
    84	  ]
    85	}
    86	{
    87	  "site": "cisco",
    88	  "specs": {
    89	    "vendor": "cisco",
    90	    "model": "ASA",
    91	    "version": "9.12(4)",
    92	    "domain": "global.dmz.example.net",
    93	    "hostname": "dmz-fw2-backup"
    94	  },
    95	  "device": "dmz-fw2-backup",
    96	  "objects": [
    97	    {
    98	      "object": "object-group",
    99	      "type": "network",
   100	      "partner": "Watchtower-DMZ",
   101	      "description": "Global secure relay",
   102	      "items": [
   103	        "network-object host 192.0.2.50"
   104	      ],
   105	      "others": [],
   106	      "group": "Unclassified"
   107	    },
   108	    {
   109	      "object": "interface",
   110	      "type": "GigabitEthernet0/0",
   111	      "partner": false,
   112	      "description": "Guest access interface",
   113	      "items": [
   114	        "ip address 10.10.10.10 255.255.255.0"
   115	      ],
   116	      "others": [
   117	        "nameif guest"
   118	      ],
   119	      "group": "Unclassified"
   120	    },
   121	    {
   122	      "object": "object",
   123	      "type": "network",
   124	      "partner": "Shield-WiFi-Alias",
   125	      "description": "Guest NAT",
   126	      "items": [
   127	        "host 10.10.10.10"
   128	      ],
   129	      "others": [],
   130	      "group": "Unclassified"
   131	    },
   132	    {
   133	      "object": "object-group",
   134	      "type": "network",
   135	      "partner": "Sector-Wireless",
   136	      "description": "Staff WiFi clients",
   137	      "items": [
   138	        "network-object host 10.10.10.10"
   139	      ],
   140	      "others": [
   141	        "network-object host 192.168.100.100"
   142	      ],
   143	      "group": "Unclassified"
   144	    }
   145	  ]
   146	}
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json ]]
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--dmz-fw2-backup.list--20563.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27637 == \1\0\.\1\0\.\1\0\.\1\0\:\:* ]]
+ fragment=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json
+ ls -al /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json
-rw-r--r--  1 emvaldes  staff  1850 Jun  9 22:55 /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json
+ cat -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json
     1	{
     2	  "site": "fortinet",
     3	  "specs": {
     4	    "vendor": "fortinet",
     5	    "model": "FortiGate-200F",
     6	    "version": "",
     7	    "domain": "",
     8	    "hostname": "fg-campus-core"
     9	  },
    10	  "device": "fg-campus-core",
    11	  "objects": [
    12	    {
    13	      "object": "config",
    14	      "type": "firewall address",
    15	      "partner": "Hawkeye-Nest",
    16	      "description": "Remote sniper node",
    17	      "items": [
    18	        "set subnet 172.16.1.6 255.255.255.255"
    19	      ],
    20	      "others": [],
    21	      "group": "Unclassified"
    22	    },
    23	    {
    24	      "object": "config",
    25	      "type": "system interface",
    26	      "partner": "core",
    27	      "description": false,
    28	      "items": [
    29	        "set ip 10.10.10.10 255.255.255.0"
    30	      ],
    31	      "others": [
    32	        "set alias \"Campus Core Transit\""
    33	      ],
    34	      "group": "Unclassified"
    35	    }
    36	  ]
    37	}
    38	{
    39	  "site": "fortinet",
    40	  "specs": {
    41	    "vendor": "fortinet",
    42	    "model": "FortiGate-200F",
    43	    "version": "",
    44	    "domain": "",
    45	    "hostname": "fg-campus-core"
    46	  },
    47	  "device": "fg-campus-core",
    48	  "objects": [
    49	    {
    50	      "object": "config",
    51	      "type": "firewall address",
    52	      "partner": "Hawkeye-Nest",
    53	      "description": "Remote sniper node",
    54	      "items": [
    55	        "set subnet 172.16.1.6 255.255.255.255"
    56	      ],
    57	      "others": [],
    58	      "group": "Unclassified"
    59	    },
    60	    {
    61	      "object": "config",
    62	      "type": "system interface",
    63	      "partner": "core",
    64	      "description": false,
    65	      "items": [
    66	        "set ip 10.10.10.10 255.255.255.0"
    67	      ],
    68	      "others": [
    69	        "set alias \"Campus Core Transit\""
    70	      ],
    71	      "group": "Unclassified"
    72	    },
    73	    {
    74	      "object": "config",
    75	      "type": "firewall address",
    76	      "partner": "Shield-WiFi",
    77	      "description": "Wireless AP Gateway",
    78	      "items": [
    79	        "set subnet 10.10.10.10 255.255.255.255"
    80	      ],
    81	      "others": [],
    82	      "group": "Unclassified"
    83	    }
    84	  ]
    85	}
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json ]]
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-campus-core.list--8988.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27726 == \1\0\.\1\0\.\1\0\.\1\0\:\:* ]]
+ fragment=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json
+ ls -al /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json
-rw-r--r--  1 emvaldes  staff  691 Jun  9 22:55 /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json
+ cat -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json
     1	{
     2	  "site": "fortinet",
     3	  "specs": {
     4	    "vendor": "fortinet",
     5	    "model": "FortiGate-60F",
     6	    "version": "v7.2.5.F",
     7	    "domain": "",
     8	    "hostname": "fg-branch-vpn-01"
     9	  },
    10	  "device": "fg-testing-config",
    11	  "objects": [
    12	    {
    13	      "object": "config",
    14	      "type": "firewall policy",
    15	      "partner": false,
    16	      "description": false,
    17	      "items": [
    18	        "set srcaddr \"10.10.10.10\""
    19	      ],
    20	      "others": [
    21	        "edit 13",
    22	        "set name \"Remote NAT\"",
    23	        "set srcintf \"dmz\"",
    24	        "set dstintf \"wan1\"",
    25	        "set dstaddr \"203.0.113.10\"",
    26	        "set action accept",
    27	        "set logtraffic all"
    28	      ],
    29	      "group": "Unclassified"
    30	    }
    31	  ]
    32	}
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json ]]
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--fg-testing-config.list--21356.json
+ for key in "${!extract_jobs2files_mapping[@]}"
+ [[ 10.10.10.10::27462 == \1\0\.\1\0\.\1\0\.\1\0\:\:* ]]
+ fragment=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json
+ ls -al /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json
-rw-r--r--  1 emvaldes  staff  839 Jun  9 22:55 /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json
+ cat -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json
     1	{
     2	  "site": "cisco",
     3	  "specs": {
     4	    "vendor": "cisco",
     5	    "model": "",
     6	    "version": "12.2",
     7	    "domain": "",
     8	    "hostname": "campus-sw-access01"
     9	  },
    10	  "device": "campus-sw-access01",
    11	  "objects": [
    12	    {
    13	      "object": "interface",
    14	      "type": "Vlan1",
    15	      "partner": false,
    16	      "description": "Switch Mgmt",
    17	      "items": [
    18	        "ip address 192.168.0.1 255.255.255.0"
    19	      ],
    20	      "others": [],
    21	      "group": "Business-Unit-Networks"
    22	    },
    23	    {
    24	      "object": "object-group",
    25	      "type": "network",
    26	      "partner": "Floor-Networks",
    27	      "description": "End-user and service devices",
    28	      "items": [
    29	        "network-object host 10.10.10.10"
    30	      ],
    31	      "others": [
    32	        "network-object host 192.168.0.1",
    33	        "network-object host 192.168.0.100"
    34	      ],
    35	      "group": "Unclassified"
    36	    }
    37	  ]
    38	}
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json ]]
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/fragments--campus-sw-access01.list--19807.json
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json ]]
+ [[ true == true ]]
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ message 'Fragment Configuration file: [ /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json ]'
+ [[ -n Fragment Configuration file: [ /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json ] ]]
+ local 'message=Fragment Configuration file: [ /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json ]'
+ echo -e 'Fragment Configuration file: [ /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json ]'
Fragment Configuration file: [ /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json ]
+ jq -s -r '
                .[] | "\(.site)/\(.device) → \( .objects | length ) objects"
                ' /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json
misc/fw3 → 3 objects
misc/fw3 → 6 objects
cisco/access-sw1-west → 2 objects
cisco/access-sw1-west → 3 objects
cisco/dmz-fw2-backup → 2 objects
cisco/dmz-fw2-backup → 3 objects
cisco/dmz-fw2-backup → 4 objects
fortinet/fg-campus-core → 2 objects
fortinet/fg-campus-core → 3 objects
fortinet/fg-testing-config → 1 objects
cisco/campus-sw-access01 → 2 objects
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ mkdir -p /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10
+ export json_outfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/10.10.10.10.json
+ json_outfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/10.10.10.10.json
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json ]]
+ jq --raw-output --slurp --arg ipref targets/10.10.10.10.json '
                        sort_by( .site, .device ) | 
                        group_by( .site + "/" + .device )[] as $group | 
                        "- " + ( $group[0].site + "/" + $group[0].device ) + 
                        " ( " + ( $group | length | tostring ) + " fragments ) -> " + $ipref, 
                        ( 
                          $group[].objects[]? | 
                          "  • object: " + ( .object // "unknown" ) + 
                          " ( type: " + ( .type // "n/a" ) + " )" 
                        ) 
                        ' /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json
- cisco/access-sw1-west ( 2 fragments ) -> targets/10.10.10.10.json
  • object: object-group ( type: network )
  • object: interface ( type: Vlan1 )
  • object: object-group ( type: network )
  • object: interface ( type: Vlan1 )
  • object: object-group ( type: network )
- cisco/campus-sw-access01 ( 1 fragments ) -> targets/10.10.10.10.json
  • object: interface ( type: Vlan1 )
  • object: object-group ( type: network )
- cisco/dmz-fw2-backup ( 3 fragments ) -> targets/10.10.10.10.json
  • object: object-group ( type: network )
  • object: interface ( type: GigabitEthernet0/0 )
  • object: object-group ( type: network )
  • object: interface ( type: GigabitEthernet0/0 )
  • object: object ( type: network )
  • object: object-group ( type: network )
  • object: interface ( type: GigabitEthernet0/0 )
  • object: object ( type: network )
  • object: object-group ( type: network )
- fortinet/fg-campus-core ( 2 fragments ) -> targets/10.10.10.10.json
  • object: config ( type: firewall address )
  • object: config ( type: system interface )
  • object: config ( type: firewall address )
  • object: config ( type: system interface )
  • object: config ( type: firewall address )
- fortinet/fg-testing-config ( 1 fragments ) -> targets/10.10.10.10.json
  • object: config ( type: firewall policy )
- misc/fw3 ( 2 fragments ) -> targets/10.10.10.10.json
  • object: object-group ( type: network )
  • object: object-group ( type: network )
  • object: object-group ( type: network )
  • object: object-group ( type: network )
  • object: object-group ( type: network )
  • object: object-group ( type: network )
  • object: object ( type: network )
  • object: object ( type: network )
  • object: object ( type: network )
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ jq --slurp --arg target 10.10.10.10 '{
                          target: $target,
                          configs: (
                            group_by( .site + "|" + .device ) | map({
                              site: .[0].site,
                              device: .[0].device,
                              specs: .[0].specs,
                              objects: ( map( .objects[]) | unique )
                            })
                          )
                        }' /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/configs-extract--fragments.json
++ mktemp
+ tmp_merged=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.oGN81dljBx
+ local final_outfile=reports/10.10.10.10/10.10.10.10.json
++ dirname reports/10.10.10.10/10.10.10.10.json
+ mkdir -p reports/10.10.10.10
+ local 'jq_merge_expr={
        target: .[0].target,
        configs:
          (
            reduce .[].configs[] as $cfg (
              [];
              if any( .[]; .site == $cfg.site and .device == $cfg.device )
                then map(
                  if .site == $cfg.site and .device == $cfg.device
                    then .objects = (
                      ( .objects + $cfg.objects )
                      | unique_by( .type, .name, .object, ( .sets | tostring ) )
                    )
                  else . end
                )
              else . + [ $cfg ] end
            )
            | sort_by(.site, .device)
          )
      }'
+ [[ -f reports/10.10.10.10/10.10.10.10.json ]]
+ jq --slurp '{
        target: .[0].target,
        configs:
          (
            reduce .[].configs[] as $cfg (
              [];
              if any( .[]; .site == $cfg.site and .device == $cfg.device )
                then map(
                  if .site == $cfg.site and .device == $cfg.device
                    then .objects = (
                      ( .objects + $cfg.objects )
                      | unique_by( .type, .name, .object, ( .sets | tostring ) )
                    )
                  else . end
                )
              else . + [ $cfg ] end
            )
            | sort_by(.site, .device)
          )
      }' /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/10.10.10.10.json
+ mv /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.oGN81dljBx reports/10.10.10.10/10.10.10.10.json
+ rm -f /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/10.10.10.10/10.10.10.10.json
+ configs_export --config=reports/10.10.10.10/10.10.10.10.json --target=reports/reports.csv
+ oIFS=' 	
'
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --config=reports/10.10.10.10/10.10.10.10.json
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ config =~ ^(initialize|i)$ ]]
+ [[ config =~ ^(sort|s)$ ]]
+ [[ config =~ ^(target|t)$ ]]
+ [[ config =~ ^(config|c)$ ]]
+ [[ -e reports/10.10.10.10/10.10.10.10.json ]]
++ basename -- reports/10.10.10.10/10.10.10.10.json
+ [[ 10.10.10.10.json =~ \.json$ ]]
+ message 'Listing Configuration File: reports/10.10.10.10/10.10.10.10.json'
+ [[ -n Listing Configuration File: reports/10.10.10.10/10.10.10.10.json ]]
+ local 'message=Listing Configuration File: reports/10.10.10.10/10.10.10.10.json'
+ echo -e 'Listing Configuration File: reports/10.10.10.10/10.10.10.10.json'
Listing Configuration File: reports/10.10.10.10/10.10.10.10.json
+ source_config=('reports/10.10.10.10/10.10.10.10.json')
+ declare -a source_config
+ cat reports/10.10.10.10/10.10.10.10.json
+ local request_action=append
+ [[ config == \h\e\l\p ]]
+ [[ config == \d\e\b\u\g ]]
+ [[ config == \d\r\y\-\r\u\n ]]
+ [[ config == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --target=reports/reports.csv
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ target =~ ^(initialize|i)$ ]]
+ [[ target =~ ^(sort|s)$ ]]
+ [[ target =~ ^(target|t)$ ]]
+ local reports_filename=reports/reports.csv
+ [[ target =~ ^(config|c)$ ]]
+ [[ target == \h\e\l\p ]]
+ [[ target == \d\e\b\u\g ]]
+ [[ target == \d\r\y\-\r\u\n ]]
+ [[ target == \v\e\r\b\o\s\e ]]
+ IFS=' 	
'
+ [[ -z '' ]]
+ local initialize=false
+ [[ -z append ]]
+ [[ -z reports/reports.csv ]]
+ [[ -z reports/10.10.10.10/10.10.10.10.json ]]
+ [[ reports/reports.csv != false ]]
++ dirname reports/reports.csv
+ local reports_location=reports
+ mkdir -p reports
+ [[ -z true ]]
+ [[ -z false ]]
+ [[ -z true ]]
+ [[ -z false ]]
+ [[ false == true ]]
++ mktemp
+ local temporary_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.mlVy8kAHcE
+ output_structure=('target=$target' 'site=.site' 'device=.device' 'vendor=.specs.vendor' 'model=.specs.model' 'version=.specs.version' 'domain=.specs.domain' 'hostname=.specs.hostname' 'object=$obj.object' 'type=$obj.type' 'items=$obj.items[0]' 'partner=$obj.partner' 'description=$obj.description' 'group=$obj.group')
+ local -a output_structure
+ local csv_header=
+ local parameters=
+ for item in "${output_structure[@]}"
+ local index=target
+ local 'value=$target'
+ csv_header+=target,
+ [[ $target =~ // ]]
+ value='$target // "none"'
+ parameters+='$target // "none", '
+ for item in "${output_structure[@]}"
+ local index=site
+ local value=.site
+ csv_header+=site,
+ [[ .site =~ // ]]
+ value='.site // "none"'
+ parameters+='.site // "none", '
+ for item in "${output_structure[@]}"
+ local index=device
+ local value=.device
+ csv_header+=device,
+ [[ .device =~ // ]]
+ value='.device // "none"'
+ parameters+='.device // "none", '
+ for item in "${output_structure[@]}"
+ local index=vendor
+ local value=.specs.vendor
+ csv_header+=vendor,
+ [[ .specs.vendor =~ // ]]
+ value='.specs.vendor // "none"'
+ parameters+='.specs.vendor // "none", '
+ for item in "${output_structure[@]}"
+ local index=model
+ local value=.specs.model
+ csv_header+=model,
+ [[ .specs.model =~ // ]]
+ value='.specs.model // "none"'
+ parameters+='.specs.model // "none", '
+ for item in "${output_structure[@]}"
+ local index=version
+ local value=.specs.version
+ csv_header+=version,
+ [[ .specs.version =~ // ]]
+ value='.specs.version // "none"'
+ parameters+='.specs.version // "none", '
+ for item in "${output_structure[@]}"
+ local index=domain
+ local value=.specs.domain
+ csv_header+=domain,
+ [[ .specs.domain =~ // ]]
+ value='.specs.domain // "none"'
+ parameters+='.specs.domain // "none", '
+ for item in "${output_structure[@]}"
+ local index=hostname
+ local value=.specs.hostname
+ csv_header+=hostname,
+ [[ .specs.hostname =~ // ]]
+ value='.specs.hostname // "none"'
+ parameters+='.specs.hostname // "none", '
+ for item in "${output_structure[@]}"
+ local index=object
+ local 'value=$obj.object'
+ csv_header+=object,
+ [[ $obj.object =~ // ]]
+ value='$obj.object // "none"'
+ parameters+='$obj.object // "none", '
+ for item in "${output_structure[@]}"
+ local index=type
+ local 'value=$obj.type'
+ csv_header+=type,
+ [[ $obj.type =~ // ]]
+ value='$obj.type // "none"'
+ parameters+='$obj.type // "none", '
+ for item in "${output_structure[@]}"
+ local index=items
+ local 'value=$obj.items[0]'
+ csv_header+=items,
+ [[ $obj.items[0] =~ // ]]
+ value='$obj.items[0] // "none"'
+ parameters+='$obj.items[0] // "none", '
+ for item in "${output_structure[@]}"
+ local index=partner
+ local 'value=$obj.partner'
+ csv_header+=partner,
+ [[ $obj.partner =~ // ]]
+ value='$obj.partner // "none"'
+ parameters+='$obj.partner // "none", '
+ for item in "${output_structure[@]}"
+ local index=description
+ local 'value=$obj.description'
+ csv_header+=description,
+ [[ $obj.description =~ // ]]
+ value='$obj.description // "none"'
+ parameters+='$obj.description // "none", '
+ for item in "${output_structure[@]}"
+ local index=group
+ local 'value=$obj.group'
+ csv_header+=group,
+ [[ $obj.group =~ // ]]
+ value='$obj.group // "none"'
+ parameters+='$obj.group // "none", '
+ parameters='$target // "none", .site // "none", .device // "none", .specs.vendor // "none", .specs.model // "none", .specs.version // "none", .specs.domain // "none", .specs.hostname // "none", $obj.object // "none", $obj.type // "none", $obj.items[0] // "none", $obj.partner // "none", $obj.description // "none", $obj.group // "none"'
+ [[ false == true ]]
+ message 'Skipping Initialization'
+ [[ -n Skipping Initialization ]]
+ local 'message=Skipping Initialization'
+ echo -e 'Skipping Initialization'
Skipping Initialization
+ [[ 1 -gt 0 ]]
+ printf '%s\n' reports/10.10.10.10/10.10.10.10.json
+ read -r json
+ message 'Processing reports/10.10.10.10/10.10.10.10.json'
+ [[ -n Processing reports/10.10.10.10/10.10.10.10.json ]]
+ local 'message=Processing reports/10.10.10.10/10.10.10.10.json'
+ echo -e 'Processing reports/10.10.10.10/10.10.10.10.json'
Processing reports/10.10.10.10/10.10.10.10.json
+ local 'json2csv_transformation=
          .target as $target
          | .configs[]
          | select( .objects != null and ( .objects | type == "array" and length > 0 ) )
          | .objects[] as $obj
          | select( (try ($obj.items | join(" ") | contains($target)) catch false) )
          | [ $target // "none", .site // "none", .device // "none", .specs.vendor // "none", .specs.model // "none", .specs.version // "none", .specs.domain // "none", .specs.hostname // "none", $obj.object // "none", $obj.type // "none", $obj.items[0] // "none", $obj.partner // "none", $obj.description // "none", $obj.group // "none" ]
          | @csv
        '
+ jq --exit-status --raw-output '
          .target as $target
          | .configs[]
          | select( .objects != null and ( .objects | type == "array" and length > 0 ) )
          | .objects[] as $obj
          | select( (try ($obj.items | join(" ") | contains($target)) catch false) )
          | [ $target // "none", .site // "none", .device // "none", .specs.vendor // "none", .specs.model // "none", .specs.version // "none", .specs.domain // "none", .specs.hostname // "none", $obj.object // "none", $obj.type // "none", $obj.items[0] // "none", $obj.partner // "none", $obj.description // "none", $obj.group // "none" ]
          | @csv
        ' reports/10.10.10.10/10.10.10.10.json
+ read -r json
+ return 0
+ [[ true == true ]]
+ print 'Merged [ targets/10.10.10.10.json ] → reports/10.10.10.10/10.10.10.10.json'
+ [[ -n Merged [ targets/10.10.10.10.json ] → reports/10.10.10.10/10.10.10.10.json ]]
+ echo -en 'Merged [ targets/10.10.10.10.json ] → reports/10.10.10.10/10.10.10.10.json'
Merged [ targets/10.10.10.10.json ] → reports/10.10.10.10/10.10.10.10.json+ newline 2
+ local count=2
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ [[ true == true ]]
+ print_file /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/configs-parser--10.10.10.10.console
+ [[ -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/configs-parser--10.10.10.10.console ]]
+ local target_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/configs-parser--10.10.10.10.console
+ [[ -f /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.90hwuJyGl8/configs-parser--10.10.10.10.console ]]
+ return 0
