+ file_extensions=()
+ declare -a file_extensions
+ oIFS=' 	
'
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --configs=reports/192.168.100.100
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ configs =~ ^(classify|g)$ ]]
+ [[ configs =~ ^(configs|c)$ ]]
+ export configs_dirpath=reports/192.168.100.100
+ configs_dirpath=reports/192.168.100.100
+ [[ configs =~ ^(file-ext|x)$ ]]
+ [[ configs =~ ^(index|n)$ ]]
+ [[ configs =~ ^(ip-addr|i)$ ]]
+ [[ configs =~ ^(logger|l)$ ]]
+ [[ configs =~ ^(matrix|m)$ ]]
+ [[ configs =~ ^(reports|r)$ ]]
+ [[ configs =~ ^(validate|v)$ ]]
+ [[ configs == \d\e\b\u\g ]]
+ [[ configs == \d\r\y\-\r\u\n ]]
+ [[ configs == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --ip-addr=192.168.100.100
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ ip-addr =~ ^(classify|g)$ ]]
+ [[ ip-addr =~ ^(configs|c)$ ]]
+ [[ ip-addr =~ ^(file-ext|x)$ ]]
+ [[ ip-addr =~ ^(index|n)$ ]]
+ [[ ip-addr =~ ^(ip-addr|i)$ ]]
+ local target_address=192.168.100.100
+ [[ ip-addr =~ ^(logger|l)$ ]]
+ [[ ip-addr =~ ^(matrix|m)$ ]]
+ [[ ip-addr =~ ^(reports|r)$ ]]
+ [[ ip-addr =~ ^(validate|v)$ ]]
+ [[ ip-addr == \d\e\b\u\g ]]
+ [[ ip-addr == \d\r\y\-\r\u\n ]]
+ [[ ip-addr == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --index=5
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ index =~ ^(classify|g)$ ]]
+ [[ index =~ ^(configs|c)$ ]]
+ [[ index =~ ^(file-ext|x)$ ]]
+ [[ index =~ ^(index|n)$ ]]
+ local target_index=5
+ [[ index =~ ^(ip-addr|i)$ ]]
+ [[ index =~ ^(logger|l)$ ]]
+ [[ index =~ ^(matrix|m)$ ]]
+ [[ index =~ ^(reports|r)$ ]]
+ [[ index =~ ^(validate|v)$ ]]
+ [[ index == \d\e\b\u\g ]]
+ [[ index == \d\r\y\-\r\u\n ]]
+ [[ index == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --matrix=matrix.json
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ matrix =~ ^(classify|g)$ ]]
+ [[ matrix =~ ^(configs|c)$ ]]
+ [[ matrix =~ ^(file-ext|x)$ ]]
+ [[ matrix =~ ^(index|n)$ ]]
+ [[ matrix =~ ^(ip-addr|i)$ ]]
+ [[ matrix =~ ^(logger|l)$ ]]
+ [[ matrix =~ ^(matrix|m)$ ]]
+ local matrix_filename=matrix.json
+ [[ matrix =~ ^(reports|r)$ ]]
+ [[ matrix =~ ^(validate|v)$ ]]
+ [[ matrix == \d\e\b\u\g ]]
+ [[ matrix == \d\r\y\-\r\u\n ]]
+ [[ matrix == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --reports=reports
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ reports =~ ^(classify|g)$ ]]
+ [[ reports =~ ^(configs|c)$ ]]
+ [[ reports =~ ^(file-ext|x)$ ]]
+ [[ reports =~ ^(index|n)$ ]]
+ [[ reports =~ ^(ip-addr|i)$ ]]
+ [[ reports =~ ^(logger|l)$ ]]
+ [[ reports =~ ^(matrix|m)$ ]]
+ [[ reports =~ ^(reports|r)$ ]]
+ local reports_location=reports
+ [[ reports =~ ^(validate|v)$ ]]
+ [[ reports == \d\e\b\u\g ]]
+ [[ reports == \d\r\y\-\r\u\n ]]
+ [[ reports == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --file-ext=cfg,conf
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ file-ext =~ ^(classify|g)$ ]]
+ [[ file-ext =~ ^(configs|c)$ ]]
+ [[ file-ext =~ ^(file-ext|x)$ ]]
+ file_extensions+=($(print "${value}" | tr ':,;\n ' '\n'))
++ print cfg,conf
++ [[ -n cfg,conf ]]
++ echo -en cfg,conf
++ tr ':,;\n ' '\n'
+ [[ file-ext =~ ^(index|n)$ ]]
+ [[ file-ext =~ ^(ip-addr|i)$ ]]
+ [[ file-ext =~ ^(logger|l)$ ]]
+ [[ file-ext =~ ^(matrix|m)$ ]]
+ [[ file-ext =~ ^(reports|r)$ ]]
+ [[ file-ext =~ ^(validate|v)$ ]]
+ [[ file-ext == \d\e\b\u\g ]]
+ [[ file-ext == \d\r\y\-\r\u\n ]]
+ [[ file-ext == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.100.100.console
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ logger =~ ^(classify|g)$ ]]
+ [[ logger =~ ^(configs|c)$ ]]
+ [[ logger =~ ^(file-ext|x)$ ]]
+ [[ logger =~ ^(index|n)$ ]]
+ [[ logger =~ ^(ip-addr|i)$ ]]
+ [[ logger =~ ^(logger|l)$ ]]
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.100.100.console
+ [[ logger =~ ^(matrix|m)$ ]]
+ [[ logger =~ ^(reports|r)$ ]]
+ [[ logger =~ ^(validate|v)$ ]]
+ [[ logger == \d\e\b\u\g ]]
+ [[ logger == \d\r\y\-\r\u\n ]]
+ [[ logger == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --classify
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ classify =~ ^(classify|g)$ ]]
+ export classify_targets=true
+ classify_targets=true
+ [[ classify =~ ^(configs|c)$ ]]
+ [[ classify =~ ^(file-ext|x)$ ]]
+ [[ classify =~ ^(index|n)$ ]]
+ [[ classify =~ ^(ip-addr|i)$ ]]
+ [[ classify =~ ^(logger|l)$ ]]
+ [[ classify =~ ^(matrix|m)$ ]]
+ [[ classify =~ ^(reports|r)$ ]]
+ [[ classify =~ ^(validate|v)$ ]]
+ [[ classify == \d\e\b\u\g ]]
+ [[ classify == \d\r\y\-\r\u\n ]]
+ [[ classify == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --verbose
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ verbose =~ ^(classify|g)$ ]]
+ [[ verbose =~ ^(configs|c)$ ]]
+ [[ verbose =~ ^(file-ext|x)$ ]]
+ [[ verbose =~ ^(index|n)$ ]]
+ [[ verbose =~ ^(ip-addr|i)$ ]]
+ [[ verbose =~ ^(logger|l)$ ]]
+ [[ verbose =~ ^(matrix|m)$ ]]
+ [[ verbose =~ ^(reports|r)$ ]]
+ [[ verbose =~ ^(validate|v)$ ]]
+ [[ verbose == \d\e\b\u\g ]]
+ [[ verbose == \d\r\y\-\r\u\n ]]
+ [[ verbose == \v\e\r\b\o\s\e ]]
+ export verbose=true
+ verbose=true
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --debug
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ debug =~ ^(classify|g)$ ]]
+ [[ debug =~ ^(configs|c)$ ]]
+ [[ debug =~ ^(file-ext|x)$ ]]
+ [[ debug =~ ^(index|n)$ ]]
+ [[ debug =~ ^(ip-addr|i)$ ]]
+ [[ debug =~ ^(logger|l)$ ]]
+ [[ debug =~ ^(matrix|m)$ ]]
+ [[ debug =~ ^(reports|r)$ ]]
+ [[ debug =~ ^(validate|v)$ ]]
+ [[ debug == \d\e\b\u\g ]]
+ export debug=true
+ debug=true
+ [[ debug == \d\r\y\-\r\u\n ]]
+ [[ debug == \v\e\r\b\o\s\e ]]
+ IFS=' 	
'
+ [[ -z true ]]
+ [[ -z false ]]
+ [[ -z true ]]
+ [[ -z /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.100.100.console ]]
+ local extract_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ :
+ [[ -z matrix.json ]]
+ [[ ! -f matrix.json ]]
+ [[ -z true ]]
+ [[ -z x ]]
+ [[ 2 -eq 0 ]]
+ export configs_dirpath=reports/192.168.100.100
+ configs_dirpath=reports/192.168.100.100
+ source_configs=()
+ declare -ga source_configs
+ local target_configlist_json=targets/192.168.100.100.json
+ [[ ! -f targets/192.168.100.100.json ]]
+ [[ true == true ]]
+ message 'Loading target config list from: targets/192.168.100.100.json'
+ [[ -n Loading target config list from: targets/192.168.100.100.json ]]
+ local 'message=Loading target config list from: targets/192.168.100.100.json'
+ echo -e 'Loading target config list from: targets/192.168.100.100.json'
+ mapfile -t source_configs
++ jq -r '
        .locations | to_entries[] |
        .key as $site |
        .value.devices[] |
        "\($site)/.objects/\(.config.file | split(".")[0]).list"
      ' targets/192.168.100.100.json
+ [[ true == true ]]
+ message 'Found 2 configurations:'
+ [[ -n Found 2 configurations: ]]
+ local 'message=Found 2 configurations:'
+ echo -e 'Found 2 configurations:'
+ for config in "${source_configs[@]}"
+ message '  - cisco/.objects/dmz-fw2-backup.list'
+ [[ -n   - cisco/.objects/dmz-fw2-backup.list ]]
+ local 'message=  - cisco/.objects/dmz-fw2-backup.list'
+ echo -e '  - cisco/.objects/dmz-fw2-backup.list'
+ for config in "${source_configs[@]}"
+ message '  - fortinet/.objects/fg-campus-core.list'
+ [[ -n   - fortinet/.objects/fg-campus-core.list ]]
+ local 'message=  - fortinet/.objects/fg-campus-core.list'
+ echo -e '  - fortinet/.objects/fg-campus-core.list'
+ for i in "${!source_configs[@]}"
+ [[ cisco/.objects/dmz-fw2-backup.list != \r\e\p\o\r\t\s\/\1\9\2\.\1\6\8\.\1\0\0\.\1\0\0\/* ]]
+ source_configs[$i]=cisco/.objects/dmz-fw2-backup.list
+ [[ true == true ]]
+ [[ ! -f matrix.json ]]
+ jq -e 'length > 0' matrix.json
++ cat matrix.json
+ export 'matrix_configs=[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ matrix_configs='[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ export reports_location=reports
+ reports_location=reports
+ [[ -z 5 ]]
+ [[ -z false ]]
+ [[ -z 192.168.100.100 ]]
++ print 192.168.100.100
++ [[ -n 192.168.100.100 ]]
++ echo -en 192.168.100.100
++ sed -E 's/[[:space:]]+//g'
++ tr -d '\r'
+ target_address=192.168.100.100
+ [[ false == true ]]
+ export tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ for cfg_file in "${source_configs[@]}"
+ extract_configs cisco/.objects/dmz-fw2-backup.list 192.168.100.100 targets/192.168.100.100.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=cisco/.objects/dmz-fw2-backup.list
+ local target_pattern=192.168.100.100
+ local target_listing=targets/192.168.100.100.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ -n Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ -n Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ local 'message=Loaded 3 config blocks'
+ echo -e 'Loaded 3 config blocks'
Loaded 3 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ local 'message=Loaded 3 config blocks'
+ echo -e 'Loaded 3 config blocks'
Loaded 3 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
+ [[ -n Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment ]]
+ local 'message=Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
+ echo -e 'Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
+ local cfg_path=cisco/.objects/dmz-fw2-backup.list
+ local rel_path=cisco/.objects/dmz-fw2-backup.list
+ local site=cisco
+ local device_filename=.objects/dmz-fw2-backup.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/cisco
+ local objects_file=reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ [[ -s reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
++ echo 'interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
++ tr '\n' '\r'
+ local 'restored_flat=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
++ tr '\n' '\r'
+ local 'objects_flat=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segmentobject network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IPobject-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
+ [[ -n Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP ]]
+ local 'message=Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
+ echo -e 'Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
+ local cfg_path=cisco/.objects/dmz-fw2-backup.list
+ local rel_path=cisco/.objects/dmz-fw2-backup.list
+ local site=cisco
+ local device_filename=.objects/dmz-fw2-backup.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/cisco
+ local objects_file=reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ [[ -s reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
++ echo 'object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
++ tr '\n' '\r'
+ local 'restored_flat=object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
++ tr '\n' '\r'
+ local 'objects_flat=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segmentobject network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IPobject-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ local cfg_path=cisco/.objects/dmz-fw2-backup.list
+ local rel_path=cisco/.objects/dmz-fw2-backup.list
+ local site=cisco
+ local device_filename=.objects/dmz-fw2-backup.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/cisco
+ local objects_file=reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ [[ -s reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
++ echo 'object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'restored_flat=object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'objects_flat=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segmentobject network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IPobject-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ continue
+ return 0
+ for cfg_file in "${source_configs[@]}"
+ extract_configs fortinet/.objects/fg-campus-core.list 192.168.100.100 targets/192.168.100.100.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=fortinet/.objects/fg-campus-core.list
+ local target_pattern=192.168.100.100
+ local target_listing=targets/192.168.100.100.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ -n Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end ]]
+ local 'message=Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ echo -e 'Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ -n Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end ]]
+ local 'message=Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ echo -e 'Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ local 'message=Loaded 3 config blocks'
+ echo -e 'Loaded 3 config blocks'
Loaded 3 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ local 'message=Loaded 3 config blocks'
+ echo -e 'Loaded 3 config blocks'
Loaded 3 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ -n Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end ]]
+ local 'message=Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ echo -e 'Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ local cfg_path=fortinet/.objects/fg-campus-core.list
+ local rel_path=fortinet/.objects/fg-campus-core.list
+ local site=fortinet
+ local device_filename=.objects/fg-campus-core.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/fortinet
+ local objects_file=reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ [[ -s reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
++ echo 'config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'restored_flat=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'objects_flat=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ grep -Fq -- 'config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ -n Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end ]]
+ local 'message=Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ echo -e 'Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ local cfg_path=fortinet/.objects/fg-campus-core.list
+ local rel_path=fortinet/.objects/fg-campus-core.list
+ local site=fortinet
+ local device_filename=.objects/fg-campus-core.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/fortinet
+ local objects_file=reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ [[ -s reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
++ echo 'config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'restored_flat=config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'objects_flat=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ grep -Fq -- 'config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ local cfg_path=fortinet/.objects/fg-campus-core.list
+ local rel_path=fortinet/.objects/fg-campus-core.list
+ local site=fortinet
+ local device_filename=.objects/fg-campus-core.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/fortinet
+ local objects_file=reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ [[ -s reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
++ echo 'config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'restored_flat=config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'objects_flat=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ grep -Fq -- 'config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ continue
+ return 0
+ [[ true == true ]]
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json ]]
+ for i in "${!source_configs[@]}"
+ [[ fortinet/.objects/fg-campus-core.list != \r\e\p\o\r\t\s\/\1\9\2\.\1\6\8\.\1\0\0\.\1\0\0\/* ]]
+ source_configs[$i]=fortinet/.objects/fg-campus-core.list
+ [[ true == true ]]
+ [[ ! -f matrix.json ]]
+ jq -e 'length > 0' matrix.json
++ cat matrix.json
+ export 'matrix_configs=[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ matrix_configs='[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ export reports_location=reports
+ reports_location=reports
+ [[ -z 5 ]]
+ [[ -z false ]]
+ [[ -z 192.168.100.100 ]]
++ print 192.168.100.100
++ [[ -n 192.168.100.100 ]]
++ echo -en 192.168.100.100
++ sed -E 's/[[:space:]]+//g'
++ tr -d '\r'
+ target_address=192.168.100.100
+ [[ false == true ]]
+ export tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ for cfg_file in "${source_configs[@]}"
+ extract_configs cisco/.objects/dmz-fw2-backup.list 192.168.100.100 targets/192.168.100.100.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=cisco/.objects/dmz-fw2-backup.list
+ local target_pattern=192.168.100.100
+ local target_listing=targets/192.168.100.100.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ -n Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
Imported Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ -n Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
Sanitized Content: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ local 'message=Loaded 3 config blocks'
+ echo -e 'Loaded 3 config blocks'
Loaded 3 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ local 'message=Loaded 3 config blocks'
+ echo -e 'Loaded 3 config blocks'
Loaded 3 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
+ [[ -n Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment ]]
+ local 'message=Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
+ echo -e 'Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
Serialized Line: interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
+ local cfg_path=cisco/.objects/dmz-fw2-backup.list
+ local rel_path=cisco/.objects/dmz-fw2-backup.list
+ local site=cisco
+ local device_filename=.objects/dmz-fw2-backup.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/cisco
+ local objects_file=reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ [[ -s reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
++ echo 'interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
++ tr '\n' '\r'
+ local 'restored_flat=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
++ tr '\n' '\r'
+ local 'objects_flat=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segmentobject network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IPobject-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segment'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
+ [[ -n Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP ]]
+ local 'message=Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
+ echo -e 'Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
Serialized Line: object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
+ local cfg_path=cisco/.objects/dmz-fw2-backup.list
+ local rel_path=cisco/.objects/dmz-fw2-backup.list
+ local site=cisco
+ local device_filename=.objects/dmz-fw2-backup.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/cisco
+ local objects_file=reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ [[ -s reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
++ echo 'object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
++ tr '\n' '\r'
+ local 'restored_flat=object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
++ tr '\n' '\r'
+ local 'objects_flat=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segmentobject network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IPobject-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IP'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ local cfg_path=cisco/.objects/dmz-fw2-backup.list
+ local rel_path=cisco/.objects/dmz-fw2-backup.list
+ local site=cisco
+ local device_filename=.objects/dmz-fw2-backup.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/cisco
+ local objects_file=reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ [[ -s reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
++ echo 'object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'restored_flat=object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'objects_flat=interface GigabitEthernet0/1--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  nameif inside--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  ip address 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Inside LAN segmentobject network Titan-WLAN-Host--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Backup inside NAT IPobject-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object-group network Sector-Wireless--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  description Staff WiFi clients--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 192.168.100.100--MTc0OTAzMjEyOTIwNTgwNDAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list'
Skipping duplicate block in reports/192.168.100.100/cisco/.objects/dmz-fw2-backup.list
+ continue
+ return 0
+ for cfg_file in "${source_configs[@]}"
+ extract_configs fortinet/.objects/fg-campus-core.list 192.168.100.100 targets/192.168.100.100.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=fortinet/.objects/fg-campus-core.list
+ local target_pattern=192.168.100.100
+ local target_listing=targets/192.168.100.100.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ -n Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end ]]
+ local 'message=Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ echo -e 'Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
Imported Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ -n Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end ]]
+ local 'message=Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ echo -e 'Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
Sanitized Content: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ local 'message=Loaded 3 config blocks'
+ echo -e 'Loaded 3 config blocks'
Loaded 3 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.100\.100([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ local 'message=Loaded 3 config blocks'
+ echo -e 'Loaded 3 config blocks'
Loaded 3 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ -n Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end ]]
+ local 'message=Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ echo -e 'Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
Serialized Line: config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ local cfg_path=fortinet/.objects/fg-campus-core.list
+ local rel_path=fortinet/.objects/fg-campus-core.list
+ local site=fortinet
+ local device_filename=.objects/fg-campus-core.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/fortinet
+ local objects_file=reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ [[ -s reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
++ echo 'config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'restored_flat=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'objects_flat=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ grep -Fq -- 'config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ -n Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end ]]
+ local 'message=Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ echo -e 'Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ local cfg_path=fortinet/.objects/fg-campus-core.list
+ local rel_path=fortinet/.objects/fg-campus-core.list
+ local site=fortinet
+ local device_filename=.objects/fg-campus-core.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/fortinet
+ local objects_file=reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ [[ -s reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
++ echo 'config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'restored_flat=config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'objects_flat=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ grep -Fq -- 'config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ local cfg_path=fortinet/.objects/fg-campus-core.list
+ local rel_path=fortinet/.objects/fg-campus-core.list
+ local site=fortinet
+ local device_filename=.objects/fg-campus-core.list
+ local extension=list
+ local objects_dir=reports/192.168.100.100/fortinet
+ local objects_file=reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ [[ -s reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
++ echo 'config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'restored_flat=config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
++ tr '\n' '\r'
+ local 'objects_flat=config system interface--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "wifi"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set ip 192.168.100.100 255.255.255.0--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set alias "Wireless VLAN"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Titan-WLAN-Host"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Guest WiFi node"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- endconfig firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ grep -Fq -- 'config firewall address--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  edit "Wanda-Field"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set subnet 192.168.100.100 255.255.255.255--MTc0OTAzMjEyOTIzNDUzNTAwMAo--   set comment "Wanda’s chaos relay"--MTc0OTAzMjEyOTIzNDUzNTAwMAo--  next--MTc0OTAzMjEyOTIzNDUzNTAwMAo-- end'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ [[ -n Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
+ echo -e 'Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list'
Skipping duplicate block in reports/192.168.100.100/fortinet/.objects/fg-campus-core.list
+ continue
+ return 0
+ [[ true == true ]]
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json ]]
+ [[ true == true ]]
+ print_file /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ [[ -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log ]]
+ local target_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ [[ -f /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log ]]
+ case "${target_file}" in
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ mkdir -p /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/192.168.100.100
+ export json_outfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/192.168.100.100/192.168.100.100.json
+ json_outfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/192.168.100.100/192.168.100.100.json
+ [[ true == true ]]
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json ]]
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json ]]
+ [[ true == true ]]
+ print_file /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.100.100.console
+ [[ -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.100.100.console ]]
+ local target_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.100.100.console
+ [[ -f /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.100.100.console ]]
+ case "${target_file}" in
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.100.100.console
+ return 0
