+ file_extensions=()
+ declare -a file_extensions
+ oIFS=' 	
'
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --configs=reports/192.168.0.1
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ configs =~ ^(classify|g)$ ]]
+ [[ configs =~ ^(configs|c)$ ]]
+ export configs_dirpath=reports/192.168.0.1
+ configs_dirpath=reports/192.168.0.1
+ [[ configs =~ ^(file-ext|x)$ ]]
+ [[ configs =~ ^(index|n)$ ]]
+ [[ configs =~ ^(ip-addr|i)$ ]]
+ [[ configs =~ ^(logger|l)$ ]]
+ [[ configs =~ ^(matrix|m)$ ]]
+ [[ configs =~ ^(reports|r)$ ]]
+ [[ configs =~ ^(validate|v)$ ]]
+ [[ configs == \d\e\b\u\g ]]
+ [[ configs == \d\r\y\-\r\u\n ]]
+ [[ configs == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --ip-addr=192.168.0.1
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ ip-addr =~ ^(classify|g)$ ]]
+ [[ ip-addr =~ ^(configs|c)$ ]]
+ [[ ip-addr =~ ^(file-ext|x)$ ]]
+ [[ ip-addr =~ ^(index|n)$ ]]
+ [[ ip-addr =~ ^(ip-addr|i)$ ]]
+ local target_address=192.168.0.1
+ [[ ip-addr =~ ^(logger|l)$ ]]
+ [[ ip-addr =~ ^(matrix|m)$ ]]
+ [[ ip-addr =~ ^(reports|r)$ ]]
+ [[ ip-addr =~ ^(validate|v)$ ]]
+ [[ ip-addr == \d\e\b\u\g ]]
+ [[ ip-addr == \d\r\y\-\r\u\n ]]
+ [[ ip-addr == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --index=10
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ index =~ ^(classify|g)$ ]]
+ [[ index =~ ^(configs|c)$ ]]
+ [[ index =~ ^(file-ext|x)$ ]]
+ [[ index =~ ^(index|n)$ ]]
+ local target_index=10
+ [[ index =~ ^(ip-addr|i)$ ]]
+ [[ index =~ ^(logger|l)$ ]]
+ [[ index =~ ^(matrix|m)$ ]]
+ [[ index =~ ^(reports|r)$ ]]
+ [[ index =~ ^(validate|v)$ ]]
+ [[ index == \d\e\b\u\g ]]
+ [[ index == \d\r\y\-\r\u\n ]]
+ [[ index == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --matrix=matrix.json
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ matrix =~ ^(classify|g)$ ]]
+ [[ matrix =~ ^(configs|c)$ ]]
+ [[ matrix =~ ^(file-ext|x)$ ]]
+ [[ matrix =~ ^(index|n)$ ]]
+ [[ matrix =~ ^(ip-addr|i)$ ]]
+ [[ matrix =~ ^(logger|l)$ ]]
+ [[ matrix =~ ^(matrix|m)$ ]]
+ local matrix_filename=matrix.json
+ [[ matrix =~ ^(reports|r)$ ]]
+ [[ matrix =~ ^(validate|v)$ ]]
+ [[ matrix == \d\e\b\u\g ]]
+ [[ matrix == \d\r\y\-\r\u\n ]]
+ [[ matrix == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --reports=reports
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ reports =~ ^(classify|g)$ ]]
+ [[ reports =~ ^(configs|c)$ ]]
+ [[ reports =~ ^(file-ext|x)$ ]]
+ [[ reports =~ ^(index|n)$ ]]
+ [[ reports =~ ^(ip-addr|i)$ ]]
+ [[ reports =~ ^(logger|l)$ ]]
+ [[ reports =~ ^(matrix|m)$ ]]
+ [[ reports =~ ^(reports|r)$ ]]
+ local reports_location=reports
+ [[ reports =~ ^(validate|v)$ ]]
+ [[ reports == \d\e\b\u\g ]]
+ [[ reports == \d\r\y\-\r\u\n ]]
+ [[ reports == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --file-ext=cfg,conf
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ file-ext =~ ^(classify|g)$ ]]
+ [[ file-ext =~ ^(configs|c)$ ]]
+ [[ file-ext =~ ^(file-ext|x)$ ]]
+ file_extensions+=($(print "${value}" | tr ':,;\n ' '\n'))
++ print cfg,conf
++ [[ -n cfg,conf ]]
++ echo -en cfg,conf
++ tr ':,;\n ' '\n'
+ [[ file-ext =~ ^(index|n)$ ]]
+ [[ file-ext =~ ^(ip-addr|i)$ ]]
+ [[ file-ext =~ ^(logger|l)$ ]]
+ [[ file-ext =~ ^(matrix|m)$ ]]
+ [[ file-ext =~ ^(reports|r)$ ]]
+ [[ file-ext =~ ^(validate|v)$ ]]
+ [[ file-ext == \d\e\b\u\g ]]
+ [[ file-ext == \d\r\y\-\r\u\n ]]
+ [[ file-ext == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --logger=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.0.1.console
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ logger =~ ^(classify|g)$ ]]
+ [[ logger =~ ^(configs|c)$ ]]
+ [[ logger =~ ^(file-ext|x)$ ]]
+ [[ logger =~ ^(index|n)$ ]]
+ [[ logger =~ ^(ip-addr|i)$ ]]
+ [[ logger =~ ^(logger|l)$ ]]
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.0.1.console
+ [[ logger =~ ^(matrix|m)$ ]]
+ [[ logger =~ ^(reports|r)$ ]]
+ [[ logger =~ ^(validate|v)$ ]]
+ [[ logger == \d\e\b\u\g ]]
+ [[ logger == \d\r\y\-\r\u\n ]]
+ [[ logger == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --classify
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ classify =~ ^(classify|g)$ ]]
+ export classify_targets=true
+ classify_targets=true
+ [[ classify =~ ^(configs|c)$ ]]
+ [[ classify =~ ^(file-ext|x)$ ]]
+ [[ classify =~ ^(index|n)$ ]]
+ [[ classify =~ ^(ip-addr|i)$ ]]
+ [[ classify =~ ^(logger|l)$ ]]
+ [[ classify =~ ^(matrix|m)$ ]]
+ [[ classify =~ ^(reports|r)$ ]]
+ [[ classify =~ ^(validate|v)$ ]]
+ [[ classify == \d\e\b\u\g ]]
+ [[ classify == \d\r\y\-\r\u\n ]]
+ [[ classify == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --verbose
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ verbose =~ ^(classify|g)$ ]]
+ [[ verbose =~ ^(configs|c)$ ]]
+ [[ verbose =~ ^(file-ext|x)$ ]]
+ [[ verbose =~ ^(index|n)$ ]]
+ [[ verbose =~ ^(ip-addr|i)$ ]]
+ [[ verbose =~ ^(logger|l)$ ]]
+ [[ verbose =~ ^(matrix|m)$ ]]
+ [[ verbose =~ ^(reports|r)$ ]]
+ [[ verbose =~ ^(validate|v)$ ]]
+ [[ verbose == \d\e\b\u\g ]]
+ [[ verbose == \d\r\y\-\r\u\n ]]
+ [[ verbose == \v\e\r\b\o\s\e ]]
+ export verbose=true
+ verbose=true
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --debug
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ debug =~ ^(classify|g)$ ]]
+ [[ debug =~ ^(configs|c)$ ]]
+ [[ debug =~ ^(file-ext|x)$ ]]
+ [[ debug =~ ^(index|n)$ ]]
+ [[ debug =~ ^(ip-addr|i)$ ]]
+ [[ debug =~ ^(logger|l)$ ]]
+ [[ debug =~ ^(matrix|m)$ ]]
+ [[ debug =~ ^(reports|r)$ ]]
+ [[ debug =~ ^(validate|v)$ ]]
+ [[ debug == \d\e\b\u\g ]]
+ export debug=true
+ debug=true
+ [[ debug == \d\r\y\-\r\u\n ]]
+ [[ debug == \v\e\r\b\o\s\e ]]
+ IFS=' 	
'
+ [[ -z true ]]
+ [[ -z false ]]
+ [[ -z true ]]
+ [[ -z /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.0.1.console ]]
+ local extract_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ :
+ [[ -z matrix.json ]]
+ [[ ! -f matrix.json ]]
+ [[ -z true ]]
+ [[ -z x ]]
+ [[ 2 -eq 0 ]]
+ export configs_dirpath=reports/192.168.0.1
+ configs_dirpath=reports/192.168.0.1
+ source_configs=()
+ declare -ga source_configs
+ local target_configlist_json=targets/192.168.0.1.json
+ [[ ! -f targets/192.168.0.1.json ]]
+ [[ true == true ]]
+ message 'Loading target config list from: targets/192.168.0.1.json'
+ [[ -n Loading target config list from: targets/192.168.0.1.json ]]
+ local 'message=Loading target config list from: targets/192.168.0.1.json'
+ echo -e 'Loading target config list from: targets/192.168.0.1.json'
+ mapfile -t source_configs
++ jq -r '
        .locations | to_entries[] |
        .key as $site |
        .value.devices[] |
        "\($site)/.objects/\(.config.file | split(".")[0]).list"
      ' targets/192.168.0.1.json
+ [[ true == true ]]
+ message 'Found 3 configurations:'
+ [[ -n Found 3 configurations: ]]
+ local 'message=Found 3 configurations:'
+ echo -e 'Found 3 configurations:'
+ for config in "${source_configs[@]}"
+ message '  - cisco/.objects/access-sw1-west.list'
+ [[ -n   - cisco/.objects/access-sw1-west.list ]]
+ local 'message=  - cisco/.objects/access-sw1-west.list'
+ echo -e '  - cisco/.objects/access-sw1-west.list'
+ for config in "${source_configs[@]}"
+ message '  - cisco/.objects/campus-sw-access01.list'
+ [[ -n   - cisco/.objects/campus-sw-access01.list ]]
+ local 'message=  - cisco/.objects/campus-sw-access01.list'
+ echo -e '  - cisco/.objects/campus-sw-access01.list'
+ for config in "${source_configs[@]}"
+ message '  - fortinet/.objects/fg-branch-vpn-01.list'
+ [[ -n   - fortinet/.objects/fg-branch-vpn-01.list ]]
+ local 'message=  - fortinet/.objects/fg-branch-vpn-01.list'
+ echo -e '  - fortinet/.objects/fg-branch-vpn-01.list'
+ for i in "${!source_configs[@]}"
+ [[ cisco/.objects/access-sw1-west.list != \r\e\p\o\r\t\s\/\1\9\2\.\1\6\8\.\0\.\1\/* ]]
+ source_configs[$i]=cisco/.objects/access-sw1-west.list
+ [[ true == true ]]
+ [[ ! -f matrix.json ]]
+ jq -e 'length > 0' matrix.json
++ cat matrix.json
+ export 'matrix_configs=[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ matrix_configs='[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ export reports_location=reports
+ reports_location=reports
+ [[ -z 10 ]]
+ [[ -z false ]]
+ [[ -z 192.168.0.1 ]]
++ print 192.168.0.1
++ [[ -n 192.168.0.1 ]]
++ sed -E 's/[[:space:]]+//g'
++ echo -en 192.168.0.1
++ tr -d '\r'
+ target_address=192.168.0.1
+ [[ false == true ]]
+ export tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ for cfg_file in "${source_configs[@]}"
+ extract_configs cisco/.objects/access-sw1-west.list 192.168.0.1 targets/192.168.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=cisco/.objects/access-sw1-west.list
+ local target_pattern=192.168.0.1
+ local target_listing=targets/192.168.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ [[ -n Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface ]]
+ local 'message=Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ echo -e 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ local cfg_path=cisco/.objects/access-sw1-west.list
+ local rel_path=cisco/.objects/access-sw1-west.list
+ local site=cisco
+ local device_filename=.objects/access-sw1-west.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ [[ -s reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
++ echo 'interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
++ tr '\n' '\r'
+ local 'restored_flat=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interfaceobject-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ local cfg_path=cisco/.objects/access-sw1-west.list
+ local rel_path=cisco/.objects/access-sw1-west.list
+ local site=cisco
+ local device_filename=.objects/access-sw1-west.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ [[ -s reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
++ echo 'object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'restored_flat=object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interfaceobject-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ continue
+ return 0
+ for cfg_file in "${source_configs[@]}"
+ extract_configs cisco/.objects/campus-sw-access01.list 192.168.0.1 targets/192.168.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=cisco/.objects/campus-sw-access01.list
+ local target_pattern=192.168.0.1
+ local target_listing=targets/192.168.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ [[ -n Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt ]]
+ local 'message=Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ echo -e 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ local cfg_path=cisco/.objects/campus-sw-access01.list
+ local rel_path=cisco/.objects/campus-sw-access01.list
+ local site=cisco
+ local device_filename=.objects/campus-sw-access01.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ [[ -s reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
++ echo 'interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
++ tr '\n' '\r'
+ local 'restored_flat=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmtobject-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ local cfg_path=cisco/.objects/campus-sw-access01.list
+ local rel_path=cisco/.objects/campus-sw-access01.list
+ local site=cisco
+ local device_filename=.objects/campus-sw-access01.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ [[ -s reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
++ echo 'object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'restored_flat=object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmtobject-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ continue
+ return 0
+ for cfg_file in "${source_configs[@]}"
+ extract_configs fortinet/.objects/fg-branch-vpn-01.list 192.168.0.1 targets/192.168.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=fortinet/.objects/fg-branch-vpn-01.list
+ local target_pattern=192.168.0.1
+ local target_listing=targets/192.168.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ true == true ]]
+ message 'Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ -n Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end ]]
+ local 'message=Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ echo -e 'Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ true == true ]]
+ message 'Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ -n Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end ]]
+ local 'message=Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ echo -e 'Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 1 config blocks'
+ [[ -n Loaded 1 config blocks ]]
+ local 'message=Loaded 1 config blocks'
+ echo -e 'Loaded 1 config blocks'
Loaded 1 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 1 config blocks'
+ [[ -n Loaded 1 config blocks ]]
+ local 'message=Loaded 1 config blocks'
+ echo -e 'Loaded 1 config blocks'
Loaded 1 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ local cfg_path=fortinet/.objects/fg-branch-vpn-01.list
+ local rel_path=fortinet/.objects/fg-branch-vpn-01.list
+ local site=fortinet
+ local device_filename=.objects/fg-branch-vpn-01.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/fortinet
+ local objects_file=reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list
+ [[ -s reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list ]]
++ echo 'config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
++ tr '\n' '\r'
+ local 'restored_flat=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
++ tr '\n' '\r'
+ local 'objects_flat=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ grep -Fq -- 'config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list'
Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list
+ continue
+ return 0
+ [[ true == true ]]
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json ]]
+ for i in "${!source_configs[@]}"
+ [[ cisco/.objects/campus-sw-access01.list != \r\e\p\o\r\t\s\/\1\9\2\.\1\6\8\.\0\.\1\/* ]]
+ source_configs[$i]=cisco/.objects/campus-sw-access01.list
+ [[ true == true ]]
+ [[ ! -f matrix.json ]]
+ jq -e 'length > 0' matrix.json
++ cat matrix.json
+ export 'matrix_configs=[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ matrix_configs='[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ export reports_location=reports
+ reports_location=reports
+ [[ -z 10 ]]
+ [[ -z false ]]
+ [[ -z 192.168.0.1 ]]
++ print 192.168.0.1
++ [[ -n 192.168.0.1 ]]
++ echo -en 192.168.0.1
++ sed -E 's/[[:space:]]+//g'
++ tr -d '\r'
+ target_address=192.168.0.1
+ [[ false == true ]]
+ export tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ for cfg_file in "${source_configs[@]}"
+ extract_configs cisco/.objects/access-sw1-west.list 192.168.0.1 targets/192.168.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=cisco/.objects/access-sw1-west.list
+ local target_pattern=192.168.0.1
+ local target_listing=targets/192.168.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ [[ -n Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface ]]
+ local 'message=Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ echo -e 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ local cfg_path=cisco/.objects/access-sw1-west.list
+ local rel_path=cisco/.objects/access-sw1-west.list
+ local site=cisco
+ local device_filename=.objects/access-sw1-west.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ [[ -s reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
++ echo 'interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
++ tr '\n' '\r'
+ local 'restored_flat=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interfaceobject-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ local cfg_path=cisco/.objects/access-sw1-west.list
+ local rel_path=cisco/.objects/access-sw1-west.list
+ local site=cisco
+ local device_filename=.objects/access-sw1-west.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ [[ -s reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
++ echo 'object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'restored_flat=object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interfaceobject-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ continue
+ return 0
+ for cfg_file in "${source_configs[@]}"
+ extract_configs cisco/.objects/campus-sw-access01.list 192.168.0.1 targets/192.168.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=cisco/.objects/campus-sw-access01.list
+ local target_pattern=192.168.0.1
+ local target_listing=targets/192.168.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ [[ -n Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt ]]
+ local 'message=Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ echo -e 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ local cfg_path=cisco/.objects/campus-sw-access01.list
+ local rel_path=cisco/.objects/campus-sw-access01.list
+ local site=cisco
+ local device_filename=.objects/campus-sw-access01.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ [[ -s reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
++ echo 'interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
++ tr '\n' '\r'
+ local 'restored_flat=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmtobject-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ local cfg_path=cisco/.objects/campus-sw-access01.list
+ local rel_path=cisco/.objects/campus-sw-access01.list
+ local site=cisco
+ local device_filename=.objects/campus-sw-access01.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ [[ -s reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
++ echo 'object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'restored_flat=object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmtobject-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ continue
+ return 0
+ for cfg_file in "${source_configs[@]}"
+ extract_configs fortinet/.objects/fg-branch-vpn-01.list 192.168.0.1 targets/192.168.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=fortinet/.objects/fg-branch-vpn-01.list
+ local target_pattern=192.168.0.1
+ local target_listing=targets/192.168.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ true == true ]]
+ message 'Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ -n Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end ]]
+ local 'message=Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ echo -e 'Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ true == true ]]
+ message 'Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ -n Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end ]]
+ local 'message=Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ echo -e 'Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 1 config blocks'
+ [[ -n Loaded 1 config blocks ]]
+ local 'message=Loaded 1 config blocks'
+ echo -e 'Loaded 1 config blocks'
Loaded 1 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 1 config blocks'
+ [[ -n Loaded 1 config blocks ]]
+ local 'message=Loaded 1 config blocks'
+ echo -e 'Loaded 1 config blocks'
Loaded 1 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ local cfg_path=fortinet/.objects/fg-branch-vpn-01.list
+ local rel_path=fortinet/.objects/fg-branch-vpn-01.list
+ local site=fortinet
+ local device_filename=.objects/fg-branch-vpn-01.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/fortinet
+ local objects_file=reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list
+ [[ -s reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list ]]
++ echo 'config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
++ tr '\n' '\r'
+ local 'restored_flat=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
++ tr '\n' '\r'
+ local 'objects_flat=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ grep -Fq -- 'config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list'
Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list
+ continue
+ return 0
+ [[ true == true ]]
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json ]]
+ for i in "${!source_configs[@]}"
+ [[ fortinet/.objects/fg-branch-vpn-01.list != \r\e\p\o\r\t\s\/\1\9\2\.\1\6\8\.\0\.\1\/* ]]
+ source_configs[$i]=fortinet/.objects/fg-branch-vpn-01.list
+ [[ true == true ]]
+ [[ ! -f matrix.json ]]
+ jq -e 'length > 0' matrix.json
++ cat matrix.json
+ export 'matrix_configs=[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ matrix_configs='[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ export reports_location=reports
+ reports_location=reports
+ [[ -z 10 ]]
+ [[ -z false ]]
+ [[ -z 192.168.0.1 ]]
++ print 192.168.0.1
++ [[ -n 192.168.0.1 ]]
++ echo -en 192.168.0.1
++ sed -E 's/[[:space:]]+//g'
++ tr -d '\r'
+ target_address=192.168.0.1
+ [[ false == true ]]
+ export tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ for cfg_file in "${source_configs[@]}"
+ extract_configs cisco/.objects/access-sw1-west.list 192.168.0.1 targets/192.168.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=cisco/.objects/access-sw1-west.list
+ local target_pattern=192.168.0.1
+ local target_listing=targets/192.168.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
Imported Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ [[ -n Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface ]]
+ local 'message=Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ echo -e 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
Serialized Line: interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ local cfg_path=cisco/.objects/access-sw1-west.list
+ local rel_path=cisco/.objects/access-sw1-west.list
+ local site=cisco
+ local device_filename=.objects/access-sw1-west.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ [[ -s reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
++ echo 'interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
++ tr '\n' '\r'
+ local 'restored_flat=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interfaceobject-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interface'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ local cfg_path=cisco/.objects/access-sw1-west.list
+ local rel_path=cisco/.objects/access-sw1-west.list
+ local site=cisco
+ local device_filename=.objects/access-sw1-west.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ [[ -s reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
++ echo 'object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'restored_flat=object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management Interfaceobject-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object-group network MGMT-ACCESS--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  description Management objects--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTA5MTU2NzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/access-sw1-west.list
+ continue
+ return 0
+ for cfg_file in "${source_configs[@]}"
+ extract_configs cisco/.objects/campus-sw-access01.list 192.168.0.1 targets/192.168.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=cisco/.objects/campus-sw-access01.list
+ local target_pattern=192.168.0.1
+ local target_listing=targets/192.168.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
Imported Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ -n Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10 ]]
+ local 'message=Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ echo -e 'Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
Sanitized Content: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ echo -e 'Loaded 2 config blocks'
Loaded 2 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ [[ -n Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt ]]
+ local 'message=Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ echo -e 'Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
Serialized Line: interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ local cfg_path=cisco/.objects/campus-sw-access01.list
+ local rel_path=cisco/.objects/campus-sw-access01.list
+ local site=cisco
+ local device_filename=.objects/campus-sw-access01.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ [[ -s reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
++ echo 'interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
++ tr '\n' '\r'
+ local 'restored_flat=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmtobject-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmt'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ continue
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ local cfg_path=cisco/.objects/campus-sw-access01.list
+ local rel_path=cisco/.objects/campus-sw-access01.list
+ local site=cisco
+ local device_filename=.objects/campus-sw-access01.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/cisco
+ local objects_file=reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ [[ -s reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
++ echo 'object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'restored_flat=object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
++ tr '\n' '\r'
+ local 'objects_flat=interface Vlan1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  ip address 192.168.0.1 255.255.255.0--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description Switch Mgmtobject-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ grep -Fq -- 'object-group network Floor-Networks--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  description End-user and service devices--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.1--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 192.168.0.100--MTc0OTAzMjEyOTQ2NzYwNzAwMAo--  network-object host 10.10.10.10'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list'
Skipping duplicate block in reports/192.168.0.1/cisco/.objects/campus-sw-access01.list
+ continue
+ return 0
+ for cfg_file in "${source_configs[@]}"
+ extract_configs fortinet/.objects/fg-branch-vpn-01.list 192.168.0.1 targets/192.168.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local config_file=fortinet/.objects/fg-branch-vpn-01.list
+ local target_pattern=192.168.0.1
+ local target_listing=targets/192.168.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json
+ local target_logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ local 'imported_content=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ true == true ]]
+ message 'Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ -n Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end ]]
+ local 'message=Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ echo -e 'Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
Imported Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ true == true ]]
+ message 'Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ -n Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end ]]
+ local 'message=Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ echo -e 'Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
Sanitized Content: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end
++ perl -pe 's/\n/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/g'
+ local 'serialized_objects=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ true == true ]]
+ message 'Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Objects: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ sed -E 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--([^[:space:]])/\n\1/g'
+ local 'restored_lines=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
'
+ [[ true == true ]]
+ message 'Loaded 1 config blocks'
+ [[ -n Loaded 1 config blocks ]]
+ local 'message=Loaded 1 config blocks'
+ echo -e 'Loaded 1 config blocks'
Loaded 1 config blocks
+ oIFS=' 	
'
+ IFS='
'
+ matched_objects=()
+ declare -a matched_objects
+ for block in "${config_objects[@]}"
+ grep -qE '(^|[^0-9.])192\.168\.0\.1([^0-9.]|$)'
+ matched_objects+=("${block}")
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 1 config blocks'
+ [[ -n Loaded 1 config blocks ]]
+ local 'message=Loaded 1 config blocks'
+ echo -e 'Loaded 1 config blocks'
Loaded 1 config blocks
+ local process_configs__logfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/process_configs.logs
+ :
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ [[ -n Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo-- ]]
+ local 'message=Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
+ echo -e 'Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--'
Serialized Line: config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--
++ perl -pe 's/--MTc0OTAzMjEyNjQ1NDk3OTAwMAo--/\n/g'
+ restored_block='config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ local cfg_path=fortinet/.objects/fg-branch-vpn-01.list
+ local rel_path=fortinet/.objects/fg-branch-vpn-01.list
+ local site=fortinet
+ local device_filename=.objects/fg-branch-vpn-01.list
+ local extension=list
+ local objects_dir=reports/192.168.0.1/fortinet
+ local objects_file=reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list
+ [[ -s reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list ]]
++ echo 'config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
++ tr '\n' '\r'
+ local 'restored_flat=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
++ tr '\n' '\r'
+ local 'objects_flat=config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ grep -Fq -- 'config firewall address--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  edit "Guardians-Relay"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set subnet 192.168.0.1 255.255.255.255--MTc0OTAzMjEyOTM3NTA2MTAwMAo--   set comment "Backup uplink for Milano crew"--MTc0OTAzMjEyOTM3NTA2MTAwMAo--  next--MTc0OTAzMjEyOTM3NTA2MTAwMAo-- end'
+ [[ true == true ]]
+ message 'Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list'
+ [[ -n Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list ]]
+ local 'message=Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list'
+ echo -e 'Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list'
Skipping duplicate block in reports/192.168.0.1/fortinet/.objects/fg-branch-vpn-01.list
+ continue
+ return 0
+ [[ true == true ]]
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json ]]
+ [[ true == true ]]
+ print_file /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ [[ -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log ]]
+ local target_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ [[ -f /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log ]]
+ case "${target_file}" in
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/extract-configs.log
+ mkdir -p /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/192.168.0.1
+ export json_outfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/192.168.0.1/192.168.0.1.json
+ json_outfile=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/192.168.0.1/192.168.0.1.json
+ [[ true == true ]]
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json ]]
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/fragments.json ]]
+ [[ true == true ]]
+ print_file /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.0.1.console
+ [[ -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.0.1.console ]]
+ local target_file=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.0.1.console
+ [[ -f /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.0.1.console ]]
+ case "${target_file}" in
+ cat /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.2kOFHYGkMy/configs-parser--192.168.0.1.console
+ return 0
