+ set -euo pipefail
+ export LC_ALL=C
+ LC_ALL=C
++ mktemp -d
+ export TMP_DIR=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk
+ TMP_DIR=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk
+ trap '[[ -d "${TMP_DIR}" ]] && rm -rf "${TMP_DIR}"' EXIT
+ source ./scripts/tools-devops.shell
++ [[ -n '' ]]
++ readonly __TOOLS_DEVOPS_SOURCED=1
++ __TOOLS_DEVOPS_SOURCED=1
++ [[ 5 -lt 4 ]]
++ alias log-info=log_info
++ alias log-warn=log_warn
++ alias log-error=log_error
++ alias error-message=error_message
++ alias exit-error=exit_error
++ alias detect-platform=detect_platform
++ alias install-packages=install_packages
++ alias install-missing=install_missing
++ alias display-help=display_help_generic
++ alias relative-configpath=relative_configpath
++ alias validate-address=validate_address
++ export LC_ALL=C
++ LC_ALL=C
++ export 'nl=\n'
++ nl='\n'
++ local_state_dir=.local
++ mkdir -p .local/errors .local/jobs .local/stats
++ export stats_folder=.local/stats/
++ stats_folder=.local/stats/
++ export reports_logsfile=.local/stats//reports.jobs
++ reports_logsfile=.local/stats//reports.jobs
++ export started_logsfile=.local/stats//started.jobs
++ started_logsfile=.local/stats//started.jobs
++ export success_logsfile=.local/stats//success.jobs
++ success_logsfile=.local/stats//success.jobs
++ export targets_logsfile=.local/stats//targets.jobs
++ targets_logsfile=.local/stats//targets.jobs
+++ date +%s%N
+++ base64
+++ tr -dc a-zA-Z0-9
++ export divisor=MTc0NzExMzA3MzYxMDU1NzAwMAo
++ divisor=MTc0NzExMzA3MzYxMDU1NzAwMAo
++ print 'DEBUG: divisor = '\''MTc0NzExMzA3MzYxMDU1NzAwMAo'\'''
++ [[ -n DEBUG: divisor = 'MTc0NzExMzA3MzYxMDU1NzAwMAo' ]]
++ echo -en 'DEBUG: divisor = '\''MTc0NzExMzA3MzYxMDU1NzAwMAo'\'''
DEBUG: divisor = 'MTc0NzExMzA3MzYxMDU1NzAwMAo'+ source ./scripts/tools-extraction.shell
++ [[ -n '' ]]
++ readonly __TOOLS_EXTRACTION_SOURCED=1
++ __TOOLS_EXTRACTION_SOURCED=1
++ alias extract-configs=extract_configs
++ alias process-configs=process_configs
+ alias parse-configs=main
+ matched_blocks_byfile=()
+ declare -gA matched_blocks_byfile
+ export script_name=./scripts/parse-configs.shell
+ script_name=./scripts/parse-configs.shell
+ [[ 9 -ge 1 ]]
+ [[ --configs=configs =~ ^-*(h|help)$ ]]
+ main --configs=configs --ip-addr=10.0.0.1 --index=1 --matrix=matrix.json --reports=reports --file-ext=cfg,conf,cnf --classify --verbose --debug
+ file_extensions=()
+ declare -a file_extensions
+ oIFS=' 	
'
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --configs=configs
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ configs =~ ^(classify|g)$ ]]
+ [[ configs =~ ^(file-ext|x)$ ]]
+ [[ configs =~ ^(configs|c)$ ]]
+ export configs_dirpath=configs
+ configs_dirpath=configs
+ [[ configs =~ ^(index|n)$ ]]
+ [[ configs =~ ^(ip-addr|i)$ ]]
+ [[ configs =~ ^(logs|o)$ ]]
+ [[ configs =~ ^(matrix|m)$ ]]
+ [[ configs =~ ^(reports|r)$ ]]
+ [[ configs =~ ^(validate|v)$ ]]
+ [[ configs == \h\e\l\p ]]
+ [[ configs == \d\e\b\u\g ]]
+ [[ configs == \d\r\y\-\r\u\n ]]
+ [[ configs == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --ip-addr=10.0.0.1
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ ip-addr =~ ^(classify|g)$ ]]
+ [[ ip-addr =~ ^(file-ext|x)$ ]]
+ [[ ip-addr =~ ^(configs|c)$ ]]
+ [[ ip-addr =~ ^(index|n)$ ]]
+ [[ ip-addr =~ ^(ip-addr|i)$ ]]
+ local target_address=10.0.0.1
+ [[ ip-addr =~ ^(logs|o)$ ]]
+ [[ ip-addr =~ ^(matrix|m)$ ]]
+ [[ ip-addr =~ ^(reports|r)$ ]]
+ [[ ip-addr =~ ^(validate|v)$ ]]
+ [[ ip-addr == \h\e\l\p ]]
+ [[ ip-addr == \d\e\b\u\g ]]
+ [[ ip-addr == \d\r\y\-\r\u\n ]]
+ [[ ip-addr == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --index=1
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ index =~ ^(classify|g)$ ]]
+ [[ index =~ ^(file-ext|x)$ ]]
+ [[ index =~ ^(configs|c)$ ]]
+ [[ index =~ ^(index|n)$ ]]
+ local target_index=1
+ [[ index =~ ^(ip-addr|i)$ ]]
+ [[ index =~ ^(logs|o)$ ]]
+ [[ index =~ ^(matrix|m)$ ]]
+ [[ index =~ ^(reports|r)$ ]]
+ [[ index =~ ^(validate|v)$ ]]
+ [[ index == \h\e\l\p ]]
+ [[ index == \d\e\b\u\g ]]
+ [[ index == \d\r\y\-\r\u\n ]]
+ [[ index == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --matrix=matrix.json
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ matrix =~ ^(classify|g)$ ]]
+ [[ matrix =~ ^(file-ext|x)$ ]]
+ [[ matrix =~ ^(configs|c)$ ]]
+ [[ matrix =~ ^(index|n)$ ]]
+ [[ matrix =~ ^(ip-addr|i)$ ]]
+ [[ matrix =~ ^(logs|o)$ ]]
+ [[ matrix =~ ^(matrix|m)$ ]]
+ local matrix_filename=matrix.json
+ [[ matrix =~ ^(reports|r)$ ]]
+ [[ matrix =~ ^(validate|v)$ ]]
+ [[ matrix == \h\e\l\p ]]
+ [[ matrix == \d\e\b\u\g ]]
+ [[ matrix == \d\r\y\-\r\u\n ]]
+ [[ matrix == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --reports=reports
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ reports =~ ^(classify|g)$ ]]
+ [[ reports =~ ^(file-ext|x)$ ]]
+ [[ reports =~ ^(configs|c)$ ]]
+ [[ reports =~ ^(index|n)$ ]]
+ [[ reports =~ ^(ip-addr|i)$ ]]
+ [[ reports =~ ^(logs|o)$ ]]
+ [[ reports =~ ^(matrix|m)$ ]]
+ [[ reports =~ ^(reports|r)$ ]]
+ local reports_folder=reports
+ [[ reports =~ ^(validate|v)$ ]]
+ [[ reports == \h\e\l\p ]]
+ [[ reports == \d\e\b\u\g ]]
+ [[ reports == \d\r\y\-\r\u\n ]]
+ [[ reports == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --file-ext=cfg,conf,cnf
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ file-ext =~ ^(classify|g)$ ]]
+ [[ file-ext =~ ^(file-ext|x)$ ]]
+ file_extensions+=($(print "${value}" | tr ':,;\n ' '\n'))
++ print cfg,conf,cnf
++ [[ -n cfg,conf,cnf ]]
++ echo -en cfg,conf,cnf
++ tr ':,;\n ' '\n'
+ [[ file-ext =~ ^(configs|c)$ ]]
+ [[ file-ext =~ ^(index|n)$ ]]
+ [[ file-ext =~ ^(ip-addr|i)$ ]]
+ [[ file-ext =~ ^(logs|o)$ ]]
+ [[ file-ext =~ ^(matrix|m)$ ]]
+ [[ file-ext =~ ^(reports|r)$ ]]
+ [[ file-ext =~ ^(validate|v)$ ]]
+ [[ file-ext == \h\e\l\p ]]
+ [[ file-ext == \d\e\b\u\g ]]
+ [[ file-ext == \d\r\y\-\r\u\n ]]
+ [[ file-ext == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --classify
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ classify =~ ^(classify|g)$ ]]
+ export classify_targets=true
+ classify_targets=true
+ [[ classify =~ ^(file-ext|x)$ ]]
+ [[ classify =~ ^(configs|c)$ ]]
+ [[ classify =~ ^(index|n)$ ]]
+ [[ classify =~ ^(ip-addr|i)$ ]]
+ [[ classify =~ ^(logs|o)$ ]]
+ [[ classify =~ ^(matrix|m)$ ]]
+ [[ classify =~ ^(reports|r)$ ]]
+ [[ classify =~ ^(validate|v)$ ]]
+ [[ classify == \h\e\l\p ]]
+ [[ classify == \d\e\b\u\g ]]
+ [[ classify == \d\r\y\-\r\u\n ]]
+ [[ classify == \v\e\r\b\o\s\e ]]
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --verbose
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ verbose =~ ^(classify|g)$ ]]
+ [[ verbose =~ ^(file-ext|x)$ ]]
+ [[ verbose =~ ^(configs|c)$ ]]
+ [[ verbose =~ ^(index|n)$ ]]
+ [[ verbose =~ ^(ip-addr|i)$ ]]
+ [[ verbose =~ ^(logs|o)$ ]]
+ [[ verbose =~ ^(matrix|m)$ ]]
+ [[ verbose =~ ^(reports|r)$ ]]
+ [[ verbose =~ ^(validate|v)$ ]]
+ [[ verbose == \h\e\l\p ]]
+ [[ verbose == \d\e\b\u\g ]]
+ [[ verbose == \d\r\y\-\r\u\n ]]
+ [[ verbose == \v\e\r\b\o\s\e ]]
+ export verbose=true
+ verbose=true
+ for xitem in "${@}"
+ IFS==
+ read -r key value
++ echo -e --debug
++ sed -e '1s|^\(-\)\{1,\}||'
+ [[ debug =~ ^(classify|g)$ ]]
+ [[ debug =~ ^(file-ext|x)$ ]]
+ [[ debug =~ ^(configs|c)$ ]]
+ [[ debug =~ ^(index|n)$ ]]
+ [[ debug =~ ^(ip-addr|i)$ ]]
+ [[ debug =~ ^(logs|o)$ ]]
+ [[ debug =~ ^(matrix|m)$ ]]
+ [[ debug =~ ^(reports|r)$ ]]
+ [[ debug =~ ^(validate|v)$ ]]
+ [[ debug == \h\e\l\p ]]
+ [[ debug == \d\e\b\u\g ]]
+ export debug=true
+ debug=true
+ [[ debug == \d\r\y\-\r\u\n ]]
+ [[ debug == \v\e\r\b\o\s\e ]]
+ IFS=' 	
'
+ [[ -z true ]]
+ [[ -z true ]]
+ [[ '' == true ]]
+ [[ -z true ]]
+ [[ -z x ]]
+ [[ 3 -eq 0 ]]
+ export configs_dirpath=configs
+ configs_dirpath=configs
+ source_configs=()
+ declare -ga source_configs
+ target_configlist_json=targets/10.0.0.1.json
+ [[ ! -f targets/10.0.0.1.json ]]
+ mapfile -t source_configs
++ jq -r '.configs[] | "\(.config.site)/\(.config.device)"' targets/10.0.0.1.json
+ for i in "${!source_configs[@]}"
+ [[ cisco/fw1.cfg != \c\o\n\f\i\g\s\/* ]]
+ source_configs[$i]=configs/cisco/fw1.cfg
+ for i in "${!source_configs[@]}"
+ [[ misc/switch.conf != \c\o\n\f\i\g\s\/* ]]
+ source_configs[$i]=configs/misc/switch.conf
+ [[ true == true ]]
+ print 'Config JSON file used: targets/10.0.0.1.json'
+ [[ -n Config JSON file used: targets/10.0.0.1.json ]]
+ echo -en 'Config JSON file used: targets/10.0.0.1.json'
Config JSON file used: targets/10.0.0.1.json+ print 'Extracted config paths from JSON:'
+ [[ -n Extracted config paths from JSON: ]]
+ echo -en 'Extracted config paths from JSON:'
Extracted config paths from JSON:+ for cfg in "${source_configs[@]}"
+ print ' - configs/cisco/fw1.cfg'
+ [[ -n  - configs/cisco/fw1.cfg ]]
+ echo -en ' - configs/cisco/fw1.cfg'
 - configs/cisco/fw1.cfg+ for cfg in "${source_configs[@]}"
+ print ' - configs/misc/switch.conf'
+ [[ -n  - configs/misc/switch.conf ]]
+ echo -en ' - configs/misc/switch.conf'
 - configs/misc/switch.conf+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local matrix_filename=matrix.json
+ [[ ! -f matrix.json ]]
+ jq -e 'length > 0' matrix.json
++ cat matrix.json
+ export 'matrix_configs=[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ matrix_configs='[
  {
    "match": ["BU1-NETWORK", "SOME-THING"],
    "group": "Identified Matching Entries"
  },
  {
    "match": ["Corporate HQ Subnets", "Server-192-168-1-10"],
    "group": "Business-Unit-HQ"
  },
  {
    "match": ["Remote-Site-Office", "All-Offices", "Branch-Office"],
    "group": "Business-Unit-Remote"
  },
  {
    "match": ["HQ-Server", "Production-Servers"],
    "group": "Business-Unit-Production"
  },
  {
    "match": ["Web-Server", "Data-Backup"],
    "group": "Business-Unit-Backup"
  },
  {
    "match": ["web_pool", "db_pool"],
    "group": "Business-Unit-Apps"
  },
  {
    "match": ["Vlan1", "Vlan2"],
    "group": "Business-Unit-Networks"
  },
  {
    "match": ["External-203-0-113-25"],
    "group": "Business-Unit-External"
  },
  {
    "match": ["Unused-Host"],
    "group": "Business-Unit-Orphan"
  }
]'
+ export reports_folder=reports
+ reports_folder=reports
+ mkdir -p reports/json reports/objects
+ [[ -z 1 ]]
+ [[ -z false ]]
+ [[ -z 10.0.0.1 ]]
++ print 10.0.0.1
++ [[ -n 10.0.0.1 ]]
++ sed -E 's/[[:space:]]+//g'
++ echo -en 10.0.0.1
++ tr -d '\r'
+ target_address=10.0.0.1
+ [[ false == true ]]
+ export tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ tmp_fragments=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ for cfg_file in "${source_configs[@]}"
+ extract_configs configs/cisco/fw1.cfg 10.0.0.1 targets/10.0.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ local config_file=configs/cisco/fw1.cfg
+ local target_pattern=10.0.0.1
+ local target_listing=targets/10.0.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ [[ ! -f configs/cisco/fw1.cfg ]]
+ message '[DEBUG] Checking if config file exists and is readable: configs/cisco/fw1.cfg'
+ [[ -n [DEBUG] Checking if config file exists and is readable: configs/cisco/fw1.cfg ]]
+ local 'message=[DEBUG] Checking if config file exists and is readable: configs/cisco/fw1.cfg'
+ print '[DEBUG] Checking if config file exists and is readable: configs/cisco/fw1.cfg'
+ [[ -n [DEBUG] Checking if config file exists and is readable: configs/cisco/fw1.cfg ]]
+ echo -en '[DEBUG] Checking if config file exists and is readable: configs/cisco/fw1.cfg'
[DEBUG] Checking if config file exists and is readable: configs/cisco/fw1.cfg+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ [[ ! -s configs/cisco/fw1.cfg ]]
++ stat -c%s configs/cisco/fw1.cfg
stat: illegal option -- c
usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]
+ message '[OK] File '\''configs/cisco/fw1.cfg'\'' is readable and size is  bytes'
+ [[ -n [OK] File 'configs/cisco/fw1.cfg' is readable and size is  bytes ]]
+ local 'message=[OK] File '\''configs/cisco/fw1.cfg'\'' is readable and size is  bytes'
+ print '[OK] File '\''configs/cisco/fw1.cfg'\'' is readable and size is  bytes'
+ [[ -n [OK] File 'configs/cisco/fw1.cfg' is readable and size is  bytes ]]
+ echo -en '[OK] File '\''configs/cisco/fw1.cfg'\'' is readable and size is  bytes'
[OK] File 'configs/cisco/fw1.cfg' is readable and size is  bytes+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local 'imported_content=object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
!



object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
!
!!!!!

!



object network External-203-0-113-25
 host 203.0.113.25
!


access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
!
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25
!'
+ [[ true == true ]]
+ message 'Imported Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
!



object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
!
!!!!!

!



object network External-203-0-113-25
 host 203.0.113.25
!


access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
!
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25
!'
+ [[ -n Imported Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
!



object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
!
!!!!!

!



object network External-203-0-113-25
 host 203.0.113.25
!


access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
!
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25
! ]]
+ local 'message=Imported Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
!



object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
!
!!!!!

!



object network External-203-0-113-25
 host 203.0.113.25
!


access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
!
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25
!'
+ print 'Imported Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
!



object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
!
!!!!!

!



object network External-203-0-113-25
 host 203.0.113.25
!


access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
!
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25
!'
+ [[ -n Imported Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
!



object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
!
!!!!!

!



object network External-203-0-113-25
 host 203.0.113.25
!


access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
!
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25
! ]]
+ echo -en 'Imported Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
!



object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
!
!!!!!

!



object network External-203-0-113-25
 host 203.0.113.25
!


access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
!
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25
!'
Imported Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
!



object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
!
!!!!!

!



object network External-203-0-113-25
 host 203.0.113.25
!


access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
!
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25
!+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
object network External-203-0-113-25
 host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25'
+ [[ true == true ]]
+ message 'Sanitized Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
object network External-203-0-113-25
 host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25'
+ [[ -n Sanitized Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
object network External-203-0-113-25
 host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25 ]]
+ local 'message=Sanitized Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
object network External-203-0-113-25
 host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25'
+ print 'Sanitized Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
object network External-203-0-113-25
 host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25'
+ [[ -n Sanitized Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
object network External-203-0-113-25
 host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25 ]]
+ echo -en 'Sanitized Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
object network External-203-0-113-25
 host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25'
Sanitized Content: object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10
 host 192.168.1.10
 description Main Application Server
object network External-203-0-113-25
 host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ perl -pe 's/\n/MTc0NzExMzA3MzYxMDU1NzAwMAo/g'
+ local 'serialized_objects=object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application ServerMTc0NzExMzA3MzYxMDU1NzAwMAoobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25MTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended permit ip host 10.0.0.1 anyMTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended deny ip any anyMTc0NzExMzA3MzYxMDU1NzAwMAonat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ true == true ]]
+ message 'Serialized Objects: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application ServerMTc0NzExMzA3MzYxMDU1NzAwMAoobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25MTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended permit ip host 10.0.0.1 anyMTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended deny ip any anyMTc0NzExMzA3MzYxMDU1NzAwMAonat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n Serialized Objects: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application ServerMTc0NzExMzA3MzYxMDU1NzAwMAoobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25MTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended permit ip host 10.0.0.1 anyMTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended deny ip any anyMTc0NzExMzA3MzYxMDU1NzAwMAonat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ local 'message=Serialized Objects: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application ServerMTc0NzExMzA3MzYxMDU1NzAwMAoobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25MTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended permit ip host 10.0.0.1 anyMTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended deny ip any anyMTc0NzExMzA3MzYxMDU1NzAwMAonat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ print 'Serialized Objects: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application ServerMTc0NzExMzA3MzYxMDU1NzAwMAoobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25MTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended permit ip host 10.0.0.1 anyMTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended deny ip any anyMTc0NzExMzA3MzYxMDU1NzAwMAonat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n Serialized Objects: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application ServerMTc0NzExMzA3MzYxMDU1NzAwMAoobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25MTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended permit ip host 10.0.0.1 anyMTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended deny ip any anyMTc0NzExMzA3MzYxMDU1NzAwMAonat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ echo -en 'Serialized Objects: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application ServerMTc0NzExMzA3MzYxMDU1NzAwMAoobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25MTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended permit ip host 10.0.0.1 anyMTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended deny ip any anyMTc0NzExMzA3MzYxMDU1NzAwMAonat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
Serialized Objects: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application ServerMTc0NzExMzA3MzYxMDU1NzAwMAoobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25MTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended permit ip host 10.0.0.1 anyMTc0NzExMzA3MzYxMDU1NzAwMAoaccess-list OUTSIDE extended deny ip any anyMTc0NzExMzA3MzYxMDU1NzAwMAonat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ sed -E 's/MTc0NzExMzA3MzYxMDU1NzAwMAo([^[:space:]])/\n\1/g'
+ local 'restored_lines=object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server
object network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0
object network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server
object network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25
access-list OUTSIDE extended permit ip host 10.0.0.1 any
access-list OUTSIDE extended deny ip any any
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo
'
+ [[ true == true ]]
+ message 'Loaded 6 config blocks'
+ [[ -n Loaded 6 config blocks ]]
+ local 'message=Loaded 6 config blocks'
+ print 'Loaded 6 config blocks'
+ [[ -n Loaded 6 config blocks ]]
+ echo -en 'Loaded 6 config blocks'
Loaded 6 config blocks+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!config_objects[@]}"
+ message '|---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
+ [[ -n |---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0 ]]
+ local 'message=|---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
+ print '|---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
+ [[ -n |---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0 ]]
+ echo -en '|---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
|---> Block [0]
object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!config_objects[@]}"
+ message '|---> Block [1]\nobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server'
+ [[ -n |---> Block [1]\nobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server ]]
+ local 'message=|---> Block [1]\nobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server'
+ print '|---> Block [1]\nobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server'
+ [[ -n |---> Block [1]\nobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server ]]
+ echo -en '|---> Block [1]\nobject network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server'
|---> Block [1]
object network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!config_objects[@]}"
+ message '|---> Block [2]\nobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25'
+ [[ -n |---> Block [2]\nobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25 ]]
+ local 'message=|---> Block [2]\nobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25'
+ print '|---> Block [2]\nobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25'
+ [[ -n |---> Block [2]\nobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25 ]]
+ echo -en '|---> Block [2]\nobject network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25'
|---> Block [2]
object network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!config_objects[@]}"
+ message '|---> Block [3]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n |---> Block [3]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ local 'message=|---> Block [3]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ print '|---> Block [3]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n |---> Block [3]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ echo -en '|---> Block [3]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
|---> Block [3]
access-list OUTSIDE extended permit ip host 10.0.0.1 any+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!config_objects[@]}"
+ message '|---> Block [4]\naccess-list OUTSIDE extended deny ip any any'
+ [[ -n |---> Block [4]\naccess-list OUTSIDE extended deny ip any any ]]
+ local 'message=|---> Block [4]\naccess-list OUTSIDE extended deny ip any any'
+ print '|---> Block [4]\naccess-list OUTSIDE extended deny ip any any'
+ [[ -n |---> Block [4]\naccess-list OUTSIDE extended deny ip any any ]]
+ echo -en '|---> Block [4]\naccess-list OUTSIDE extended deny ip any any'
|---> Block [4]
access-list OUTSIDE extended deny ip any any+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!config_objects[@]}"
+ message '|---> Block [5]\nnat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n |---> Block [5]\nnat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ local 'message=|---> Block [5]\nnat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ print '|---> Block [5]\nnat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n |---> Block [5]\nnat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ echo -en '|---> Block [5]\nnat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
|---> Block [5]
nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ oIFS=' 	
'
+ IFS='
'
++ printf '%s\n' 'object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0' 'object network Server-192-168-1-10MTc0NzExMzA3MzYxMDU1NzAwMAo host 192.168.1.10MTc0NzExMzA3MzYxMDU1NzAwMAo description Main Application Server' 'object network External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo host 203.0.113.25' 'access-list OUTSIDE extended permit ip host 10.0.0.1 any' 'access-list OUTSIDE extended deny ip any any' 'nat (inside,outside) source static Server-192-168-1-10 External-203-0-113-25MTc0NzExMzA3MzYxMDU1NzAwMAo'
++ grep -F 10.0.0.1
+ matched_objects=('object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0' 'access-list OUTSIDE extended permit ip host 10.0.0.1 any')
+ declare -a matched_objects
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ local 'message=Loaded 2 config blocks'
+ print 'Loaded 2 config blocks'
+ [[ -n Loaded 2 config blocks ]]
+ echo -en 'Loaded 2 config blocks'
Loaded 2 config blocks+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!matched_objects[@]}"
+ message '|---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
+ [[ -n |---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0 ]]
+ local 'message=|---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
+ print '|---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
+ [[ -n |---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0 ]]
+ echo -en '|---> Block [0]\nobject-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
|---> Block [0]
object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!matched_objects[@]}"
+ message '|---> Block [1]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n |---> Block [1]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ local 'message=|---> Block [1]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ print '|---> Block [1]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n |---> Block [1]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ echo -en '|---> Block [1]\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
|---> Block [1]
access-list OUTSIDE extended permit ip host 10.0.0.1 any+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local site_part=configs/cisco
+ local file_part=fw1.cfg
++ jq -r --arg site cisco --arg file fw1.cfg '.configs[] | select(.config.site == $site and .config.device == $file) | .count' targets/10.0.0.1.json
+ local expected_count=2
+ [[ true == true ]]
+ message 'Expected Matches (Count): 2'
+ [[ -n Expected Matches (Count): 2 ]]
+ local 'message=Expected Matches (Count): 2'
+ print 'Expected Matches (Count): 2'
+ [[ -n Expected Matches (Count): 2 ]]
+ echo -en 'Expected Matches (Count): 2'
Expected Matches (Count): 2+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ actual_count=2
+ [[ 2 != \2 ]]
+ restored_block=()
+ declare -a restored_block
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
+ [[ -n Serialized Line: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0 ]]
+ local 'message=Serialized Line: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
+ print 'Serialized Line: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
+ [[ -n Serialized Line: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0 ]]
+ echo -en 'Serialized Line: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0'
Serialized Line: object-group network BU1-NETWORKMTc0NzExMzA3MzYxMDU1NzAwMAo description Corporate HQ SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo network-object host 10.0.1.2MTc0NzExMzA3MzYxMDU1NzAwMAo network-object 192.168.1.0 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ perl -pe 's/MTc0NzExMzA3MzYxMDU1NzAwMAo/\n/g'
+ restored_block='object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
+ [[ true == true ]]
+ message 'Restored Configuration:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
+ [[ -n Restored Configuration:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0 ]]
+ local 'message=Restored Configuration:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
+ print 'Restored Configuration:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
+ [[ -n Restored Configuration:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0 ]]
+ echo -en 'Restored Configuration:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
Restored Configuration:
object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ process_configs 10.0.0.1 configs/cisco/fw1.cfg 'object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0' /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ local target_pattern=10.0.0.1
+ local config_path=configs/cisco/fw1.cfg
+ local 'restored_block=object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ local cleaned_block
++ sed '/^[[:space:]]*$/d'
+ cleaned_block='object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
+ [[ -z object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0 ]]
+ [[ true == true ]]
+ message '[process_configs] Raw Block:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
+ [[ -n [process_configs] Raw Block:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0 ]]
+ local 'message=[process_configs] Raw Block:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
+ print '[process_configs] Raw Block:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
+ [[ -n [process_configs] Raw Block:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0 ]]
+ echo -en '[process_configs] Raw Block:\nobject-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0'
[process_configs] Raw Block:
object-group network BU1-NETWORK
 description Corporate HQ Subnets
 network-object host 10.0.0.1
 network-object host 10.0.1.2
 network-object 192.168.1.0 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local object_line
++ head -n 1
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ object_line='object-group network BU1-NETWORK'
+ [[ -z object-group network BU1-NETWORK ]]
+ local object_keyword type_value
++ awk '{print $1}'
+ object_keyword=object-group
++ awk '{$1=""; print substr($0,2)}'
+ type_value='network BU1-NETWORK'
+ [[ true == true ]]
+ print '[process_configs] object   : object-group'
+ [[ -n [process_configs] object   : object-group ]]
+ echo -en '[process_configs] object   : object-group'
[process_configs] object   : object-group+ print '[process_configs] type     : network BU1-NETWORK'
+ [[ -n [process_configs] type     : network BU1-NETWORK ]]
+ echo -en '[process_configs] type     : network BU1-NETWORK'
[process_configs] type     : network BU1-NETWORK+ entries=()
+ local -a entries
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='object-group network BU1-NETWORK'
+ [[ -z object-group network BU1-NETWORK ]]
+ [[ object-group network bu1-network =~ ^description[[:space:]] ]]
+ entries+=("${trimmed}")
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='description Corporate HQ Subnets'
+ [[ -z description Corporate HQ Subnets ]]
+ [[ description corporate hq subnets =~ ^description[[:space:]] ]]
+ continue
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='network-object host 10.0.0.1'
+ [[ -z network-object host 10.0.0.1 ]]
+ [[ network-object host 10.0.0.1 =~ ^description[[:space:]] ]]
+ entries+=("${trimmed}")
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='network-object host 10.0.1.2'
+ [[ -z network-object host 10.0.1.2 ]]
+ [[ network-object host 10.0.1.2 =~ ^description[[:space:]] ]]
+ entries+=("${trimmed}")
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='network-object 192.168.1.0 255.255.255.0'
+ [[ -z network-object 192.168.1.0 255.255.255.0 ]]
+ [[ network-object 192.168.1.0 255.255.255.0 =~ ^description[[:space:]] ]]
+ entries+=("${trimmed}")
+ IFS=
+ read -r line
+ ((  4 > 1  ))
+ entries=("${entries[@]:1}")
+ [[ true == true ]]
+ message '[process_configs] Entries:'
+ [[ -n [process_configs] Entries: ]]
+ local 'message=[process_configs] Entries:'
+ print '[process_configs] Entries:'
+ [[ -n [process_configs] Entries: ]]
+ echo -en '[process_configs] Entries:'
[process_configs] Entries:+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for e in "${entries[@]}"
+ print '  - network-object host 10.0.0.1'
+ [[ -n   - network-object host 10.0.0.1 ]]
+ echo -en '  - network-object host 10.0.0.1'
  - network-object host 10.0.0.1+ for e in "${entries[@]}"
+ print '  - network-object host 10.0.1.2'
+ [[ -n   - network-object host 10.0.1.2 ]]
+ echo -en '  - network-object host 10.0.1.2'
  - network-object host 10.0.1.2+ for e in "${entries[@]}"
+ print '  - network-object 192.168.1.0 255.255.255.0'
+ [[ -n   - network-object 192.168.1.0 255.255.255.0 ]]
+ echo -en '  - network-object 192.168.1.0 255.255.255.0'
  - network-object 192.168.1.0 255.255.255.0+ local matched_line
++ grep -wF 10.0.0.1
++ head -n 1
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ matched_line='network-object host 10.0.0.1'
+ [[ -z network-object host 10.0.0.1 ]]
+ [[ true == true ]]
+ message '[process_configs] Matched: network-object host 10.0.0.1'
+ [[ -n [process_configs] Matched: network-object host 10.0.0.1 ]]
+ local 'message=[process_configs] Matched: network-object host 10.0.0.1'
+ print '[process_configs] Matched: network-object host 10.0.0.1'
+ [[ -n [process_configs] Matched: network-object host 10.0.0.1 ]]
+ echo -en '[process_configs] Matched: network-object host 10.0.0.1'
[process_configs] Matched: network-object host 10.0.0.1+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local desc_val=false
+ [[ -z false ]]
+ [[ true == true ]]
+ message '[process_configs] Description: false'
+ [[ -n [process_configs] Description: false ]]
+ local 'message=[process_configs] Description: false'
+ print '[process_configs] Description: false'
+ [[ -n [process_configs] Description: false ]]
+ echo -en '[process_configs] Description: false'
[process_configs] Description: false+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local group_val=Unclassified
+ [[ true == true ]]
+ local object_key
++ awk '{print $NF}'
++ sed -E 's/[[:punct:]]*$//'
+ object_key=BU1-NETWORK
++ jq -r --arg key BU1-NETWORK 'map(select(.match[]? | contains($key))) | .[0].group'
+ group_val='Identified Matching Entries'
+ [[ -z Identified Matching Entries ]]
+ [[ Identified Matching Entries == \n\u\l\l ]]
+ [[ -z Identified Matching Entries ]]
+ [[ Identified Matching Entries == \n\u\l\l ]]
+ [[ true == true ]]
+ message '[process_configs] Group: Identified Matching Entries'
+ [[ -n [process_configs] Group: Identified Matching Entries ]]
+ local 'message=[process_configs] Group: Identified Matching Entries'
+ print '[process_configs] Group: Identified Matching Entries'
+ [[ -n [process_configs] Group: Identified Matching Entries ]]
+ echo -en '[process_configs] Group: Identified Matching Entries'
[process_configs] Group: Identified Matching Entries+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ printf '%s\n' 'network-object host 10.0.0.1' 'network-object host 10.0.1.2' 'network-object 192.168.1.0 255.255.255.0'
++ jq -R .
++ jq -s .
+ local 'entries_2json=[
  "network-object host 10.0.0.1",
  "network-object host 10.0.1.2",
  "network-object 192.168.1.0 255.255.255.0"
]'
+ export target_object
+ [[ 3 -eq 1 ]]
++ jq -n --arg object object-group --arg type 'network BU1-NETWORK' --arg description false --argjson entries '[
  "network-object host 10.0.0.1",
  "network-object host 10.0.1.2",
  "network-object 192.168.1.0 255.255.255.0"
]' --arg group 'Identified Matching Entries' '{
                  object: $object,
                  type: $type,
                  description: ($description | select(. != "" and . != "null") // false),
                  entries: $entries,
                  group: $group
                }'
+ target_object='{
  "object": "object-group",
  "type": "network BU1-NETWORK",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object host 10.0.1.2",
    "network-object 192.168.1.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
+ [[ -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json ]]
+ [[ -n {
  "object": "object-group",
  "type": "network BU1-NETWORK",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object host 10.0.1.2",
    "network-object 192.168.1.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
} ]]
+ print '{
  "object": "object-group",
  "type": "network BU1-NETWORK",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object host 10.0.1.2",
    "network-object 192.168.1.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
+ [[ -n {
  "object": "object-group",
  "type": "network BU1-NETWORK",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object host 10.0.1.2",
    "network-object 192.168.1.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
} ]]
+ echo -en '{
  "object": "object-group",
  "type": "network BU1-NETWORK",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object host 10.0.1.2",
    "network-object 192.168.1.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
+ [[ true == true ]]
+ message '[process_configs] JSON Object (output):'
+ [[ -n [process_configs] JSON Object (output): ]]
+ local 'message=[process_configs] JSON Object (output):'
+ print '[process_configs] JSON Object (output):'
+ [[ -n [process_configs] JSON Object (output): ]]
+ echo -en '[process_configs] JSON Object (output):'
[process_configs] JSON Object (output):+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ print '{
  "object": "object-group",
  "type": "network BU1-NETWORK",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object host 10.0.1.2",
    "network-object 192.168.1.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
+ [[ -n {
  "object": "object-group",
  "type": "network BU1-NETWORK",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object host 10.0.1.2",
    "network-object 192.168.1.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
} ]]
+ echo -en '{
  "object": "object-group",
  "type": "network BU1-NETWORK",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object host 10.0.1.2",
    "network-object 192.168.1.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
+ jq .
{
  "object": "object-group",
  "type": "network BU1-NETWORK",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object host 10.0.1.2",
    "network-object 192.168.1.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ return 0
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n Serialized Line: access-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ local 'message=Serialized Line: access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ print 'Serialized Line: access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n Serialized Line: access-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ echo -en 'Serialized Line: access-list OUTSIDE extended permit ip host 10.0.0.1 any'
Serialized Line: access-list OUTSIDE extended permit ip host 10.0.0.1 any+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ perl -pe 's/MTc0NzExMzA3MzYxMDU1NzAwMAo/\n/g'
+ restored_block='access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ true == true ]]
+ message 'Restored Configuration:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n Restored Configuration:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ local 'message=Restored Configuration:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ print 'Restored Configuration:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n Restored Configuration:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ echo -en 'Restored Configuration:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
Restored Configuration:
access-list OUTSIDE extended permit ip host 10.0.0.1 any+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ process_configs 10.0.0.1 configs/cisco/fw1.cfg 'access-list OUTSIDE extended permit ip host 10.0.0.1 any' /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ local target_pattern=10.0.0.1
+ local config_path=configs/cisco/fw1.cfg
+ local 'restored_block=access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ local cleaned_block
++ sed '/^[[:space:]]*$/d'
+ cleaned_block='access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -z access-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ [[ true == true ]]
+ message '[process_configs] Raw Block:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n [process_configs] Raw Block:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ local 'message=[process_configs] Raw Block:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ print '[process_configs] Raw Block:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n [process_configs] Raw Block:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ echo -en '[process_configs] Raw Block:\naccess-list OUTSIDE extended permit ip host 10.0.0.1 any'
[process_configs] Raw Block:
access-list OUTSIDE extended permit ip host 10.0.0.1 any+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local object_line
++ head -n 1
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ object_line='access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -z access-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ local object_keyword type_value
++ awk '{print $1}'
+ object_keyword=access-list
++ awk '{$1=""; print substr($0,2)}'
+ type_value='OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ true == true ]]
+ print '[process_configs] object   : access-list'
+ [[ -n [process_configs] object   : access-list ]]
+ echo -en '[process_configs] object   : access-list'
[process_configs] object   : access-list+ print '[process_configs] type     : OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n [process_configs] type     : OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ echo -en '[process_configs] type     : OUTSIDE extended permit ip host 10.0.0.1 any'
[process_configs] type     : OUTSIDE extended permit ip host 10.0.0.1 any+ entries=()
+ local -a entries
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -z access-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ [[ access-list outside extended permit ip host 10.0.0.1 any =~ ^description[[:space:]] ]]
+ entries+=("${trimmed}")
+ IFS=
+ read -r line
+ ((  1 > 1  ))
+ [[ true == true ]]
+ message '[process_configs] Entries:'
+ [[ -n [process_configs] Entries: ]]
+ local 'message=[process_configs] Entries:'
+ print '[process_configs] Entries:'
+ [[ -n [process_configs] Entries: ]]
+ echo -en '[process_configs] Entries:'
[process_configs] Entries:+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for e in "${entries[@]}"
+ print '  - access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n   - access-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ echo -en '  - access-list OUTSIDE extended permit ip host 10.0.0.1 any'
  - access-list OUTSIDE extended permit ip host 10.0.0.1 any+ local matched_line
++ grep -wF 10.0.0.1
++ head -n 1
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ matched_line='access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -z access-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ [[ true == true ]]
+ message '[process_configs] Matched: access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n [process_configs] Matched: access-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ local 'message=[process_configs] Matched: access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ print '[process_configs] Matched: access-list OUTSIDE extended permit ip host 10.0.0.1 any'
+ [[ -n [process_configs] Matched: access-list OUTSIDE extended permit ip host 10.0.0.1 any ]]
+ echo -en '[process_configs] Matched: access-list OUTSIDE extended permit ip host 10.0.0.1 any'
[process_configs] Matched: access-list OUTSIDE extended permit ip host 10.0.0.1 any+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local desc_val=false
+ [[ -z false ]]
+ [[ true == true ]]
+ message '[process_configs] Description: false'
+ [[ -n [process_configs] Description: false ]]
+ local 'message=[process_configs] Description: false'
+ print '[process_configs] Description: false'
+ [[ -n [process_configs] Description: false ]]
+ echo -en '[process_configs] Description: false'
[process_configs] Description: false+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local group_val=Unclassified
+ [[ true == true ]]
+ local object_key
++ awk '{print $NF}'
++ sed -E 's/[[:punct:]]*$//'
+ object_key=any
++ jq -r --arg key any 'map(select(.match[]? | contains($key))) | .[0].group'
+ group_val=null
+ [[ -z null ]]
+ [[ null == \n\u\l\l ]]
++ jq -r --arg desc false 'map(select(.match[]? == $desc)) | .[0].group'
+ group_val=null
+ [[ -z null ]]
+ [[ null == \n\u\l\l ]]
+ group_val=Unclassified
+ [[ true == true ]]
+ message '[process_configs] Group: Unclassified'
+ [[ -n [process_configs] Group: Unclassified ]]
+ local 'message=[process_configs] Group: Unclassified'
+ print '[process_configs] Group: Unclassified'
+ [[ -n [process_configs] Group: Unclassified ]]
+ echo -en '[process_configs] Group: Unclassified'
[process_configs] Group: Unclassified+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ printf '%s\n' 'access-list OUTSIDE extended permit ip host 10.0.0.1 any'
++ jq -R .
++ jq -s .
+ local 'entries_2json=[
  "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
]'
+ export target_object
+ [[ 1 -eq 1 ]]
++ jq -n --arg object access-list --arg description false --argjson entries '[
  "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
]' --arg group Unclassified '{
                  object: $object,
                  type: false,
                  description: ($description | select(. != "" and . != "null") // false),
                  entries: $entries,
                  group: $group
                }'
+ target_object='{
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
}'
+ [[ -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json ]]
+ [[ -n {
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
} ]]
+ print '{
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
}'
+ [[ -n {
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
} ]]
+ echo -en '{
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
}'
+ [[ true == true ]]
+ message '[process_configs] JSON Object (output):'
+ [[ -n [process_configs] JSON Object (output): ]]
+ local 'message=[process_configs] JSON Object (output):'
+ print '[process_configs] JSON Object (output):'
+ [[ -n [process_configs] JSON Object (output): ]]
+ echo -en '[process_configs] JSON Object (output):'
[process_configs] JSON Object (output):+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ print '{
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
}'
+ [[ -n {
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
} ]]
+ jq .
+ echo -en '{
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
}'
{
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
}
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ return 0
+ [[ -s {
  "object": "access-list",
  "type": false,
  "description": "false",
  "entries": [
    "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
  ],
  "group": "Unclassified"
} ]]
+ return 0
+ for cfg_file in "${source_configs[@]}"
+ extract_configs configs/misc/switch.conf 10.0.0.1 targets/10.0.0.1.json /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ local config_file=configs/misc/switch.conf
+ local target_pattern=10.0.0.1
+ local target_listing=targets/10.0.0.1.json
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ [[ ! -f configs/misc/switch.conf ]]
+ message '[DEBUG] Checking if config file exists and is readable: configs/misc/switch.conf'
+ [[ -n [DEBUG] Checking if config file exists and is readable: configs/misc/switch.conf ]]
+ local 'message=[DEBUG] Checking if config file exists and is readable: configs/misc/switch.conf'
+ print '[DEBUG] Checking if config file exists and is readable: configs/misc/switch.conf'
+ [[ -n [DEBUG] Checking if config file exists and is readable: configs/misc/switch.conf ]]
+ echo -en '[DEBUG] Checking if config file exists and is readable: configs/misc/switch.conf'
[DEBUG] Checking if config file exists and is readable: configs/misc/switch.conf+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ [[ ! -s configs/misc/switch.conf ]]
++ stat -c%s configs/misc/switch.conf
stat: illegal option -- c
usage: stat [-FLnq] [-f format | -l | -r | -s | -x] [-t timefmt] [file ...]
+ message '[OK] File '\''configs/misc/switch.conf'\'' is readable and size is  bytes'
+ [[ -n [OK] File 'configs/misc/switch.conf' is readable and size is  bytes ]]
+ local 'message=[OK] File '\''configs/misc/switch.conf'\'' is readable and size is  bytes'
+ print '[OK] File '\''configs/misc/switch.conf'\'' is readable and size is  bytes'
+ [[ -n [OK] File 'configs/misc/switch.conf' is readable and size is  bytes ]]
+ echo -en '[OK] File '\''configs/misc/switch.conf'\'' is readable and size is  bytes'
[OK] File 'configs/misc/switch.conf' is readable and size is  bytes+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local 'imported_content=interface Vlan1
 ip address 172.31.255.254 255.255.255.0

interface Vlan2
 ip address 10.0.1.2 255.255.255.0

object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ true == true ]]
+ message 'Imported Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0

interface Vlan2
 ip address 10.0.1.2 255.255.255.0

object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ -n Imported Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0

interface Vlan2
 ip address 10.0.1.2 255.255.255.0

object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0 ]]
+ local 'message=Imported Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0

interface Vlan2
 ip address 10.0.1.2 255.255.255.0

object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ print 'Imported Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0

interface Vlan2
 ip address 10.0.1.2 255.255.255.0

object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ -n Imported Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0

interface Vlan2
 ip address 10.0.1.2 255.255.255.0

object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0 ]]
+ echo -en 'Imported Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0

interface Vlan2
 ip address 10.0.1.2 255.255.255.0

object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
Imported Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0

interface Vlan2
 ip address 10.0.1.2 255.255.255.0

object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ sed '/^\s*$/d;/^\s*!.*$/d'
+ local 'sanitized_content=interface Vlan1
 ip address 172.31.255.254 255.255.255.0
interface Vlan2
 ip address 10.0.1.2 255.255.255.0
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ true == true ]]
+ message 'Sanitized Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0
interface Vlan2
 ip address 10.0.1.2 255.255.255.0
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ -n Sanitized Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0
interface Vlan2
 ip address 10.0.1.2 255.255.255.0
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0 ]]
+ local 'message=Sanitized Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0
interface Vlan2
 ip address 10.0.1.2 255.255.255.0
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ print 'Sanitized Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0
interface Vlan2
 ip address 10.0.1.2 255.255.255.0
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ -n Sanitized Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0
interface Vlan2
 ip address 10.0.1.2 255.255.255.0
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0 ]]
+ echo -en 'Sanitized Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0
interface Vlan2
 ip address 10.0.1.2 255.255.255.0
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
Sanitized Content: interface Vlan1
 ip address 172.31.255.254 255.255.255.0
interface Vlan2
 ip address 10.0.1.2 255.255.255.0
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ perl -pe 's/\n/MTc0NzExMzA3MzYxMDU1NzAwMAo/g'
+ local 'serialized_objects=interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAointerface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ true == true ]]
+ message 'Serialized Objects: interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAointerface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n Serialized Objects: interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAointerface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ local 'message=Serialized Objects: interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAointerface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ print 'Serialized Objects: interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAointerface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n Serialized Objects: interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAointerface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ echo -en 'Serialized Objects: interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAointerface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
Serialized Objects: interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAointerface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAoobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ sed -E 's/MTc0NzExMzA3MzYxMDU1NzAwMAo([^[:space:]])/\n\1/g'
+ local 'restored_lines=interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0
interface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0
object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ restored_lines+='
'
+ IFS='
'
+ read -r -d '' -a config_objects
++ printf '%s\0' 'interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0
interface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0
object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo
'
+ [[ true == true ]]
+ message 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ local 'message=Loaded 3 config blocks'
+ print 'Loaded 3 config blocks'
+ [[ -n Loaded 3 config blocks ]]
+ echo -en 'Loaded 3 config blocks'
Loaded 3 config blocks+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!config_objects[@]}"
+ message '|---> Block [0]\ninterface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0'
+ [[ -n |---> Block [0]\ninterface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0 ]]
+ local 'message=|---> Block [0]\ninterface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0'
+ print '|---> Block [0]\ninterface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0'
+ [[ -n |---> Block [0]\ninterface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0 ]]
+ echo -en '|---> Block [0]\ninterface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0'
|---> Block [0]
interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!config_objects[@]}"
+ message '|---> Block [1]\ninterface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0'
+ [[ -n |---> Block [1]\ninterface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0 ]]
+ local 'message=|---> Block [1]\ninterface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0'
+ print '|---> Block [1]\ninterface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0'
+ [[ -n |---> Block [1]\ninterface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0 ]]
+ echo -en '|---> Block [1]\ninterface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0'
|---> Block [1]
interface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!config_objects[@]}"
+ message '|---> Block [2]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n |---> Block [2]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ local 'message=|---> Block [2]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ print '|---> Block [2]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n |---> Block [2]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ echo -en '|---> Block [2]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
|---> Block [2]
object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ oIFS=' 	
'
+ IFS='
'
++ printf '%s\n' 'interface Vlan1MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 172.31.255.254 255.255.255.0' 'interface Vlan2MTc0NzExMzA3MzYxMDU1NzAwMAo ip address 10.0.1.2 255.255.255.0' 'object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
++ grep -F 10.0.0.1
+ matched_objects=('object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo')
+ declare -a matched_objects
+ IFS=' 	
'
+ [[ true == true ]]
+ message 'Loaded 1 config blocks'
+ [[ -n Loaded 1 config blocks ]]
+ local 'message=Loaded 1 config blocks'
+ print 'Loaded 1 config blocks'
+ [[ -n Loaded 1 config blocks ]]
+ echo -en 'Loaded 1 config blocks'
Loaded 1 config blocks+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for i in "${!matched_objects[@]}"
+ message '|---> Block [0]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n |---> Block [0]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ local 'message=|---> Block [0]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ print '|---> Block [0]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n |---> Block [0]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ echo -en '|---> Block [0]\nobject-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
|---> Block [0]
object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local site_part=configs/misc
+ local file_part=switch.conf
++ jq -r --arg site misc --arg file switch.conf '.configs[] | select(.config.site == $site and .config.device == $file) | .count' targets/10.0.0.1.json
+ local expected_count=1
+ [[ true == true ]]
+ message 'Expected Matches (Count): 1'
+ [[ -n Expected Matches (Count): 1 ]]
+ local 'message=Expected Matches (Count): 1'
+ print 'Expected Matches (Count): 1'
+ [[ -n Expected Matches (Count): 1 ]]
+ echo -en 'Expected Matches (Count): 1'
Expected Matches (Count): 1+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ actual_count=1
+ [[ 1 != \1 ]]
+ restored_block=()
+ declare -a restored_block
+ for serialized_line in "${matched_objects[@]}"
+ [[ true == true ]]
+ message 'Serialized Line: object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n Serialized Line: object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ local 'message=Serialized Line: object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ print 'Serialized Line: object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
+ [[ -n Serialized Line: object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo ]]
+ echo -en 'Serialized Line: object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo'
Serialized Line: object-group network SOME-THINGMTc0NzExMzA3MzYxMDU1NzAwMAo  description Local Office SubnetsMTc0NzExMzA3MzYxMDU1NzAwMAo  network-object host 10.0.0.1MTc0NzExMzA3MzYxMDU1NzAwMAo  network-object 192.168.12.0 255.255.255.0MTc0NzExMzA3MzYxMDU1NzAwMAo+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ perl -pe 's/MTc0NzExMzA3MzYxMDU1NzAwMAo/\n/g'
+ restored_block='object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ true == true ]]
+ message 'Restored Configuration:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ -n Restored Configuration:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0 ]]
+ local 'message=Restored Configuration:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ print 'Restored Configuration:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ -n Restored Configuration:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0 ]]
+ echo -en 'Restored Configuration:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
Restored Configuration:
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ process_configs 10.0.0.1 configs/misc/switch.conf 'object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0' /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ local target_pattern=10.0.0.1
+ local config_path=configs/misc/switch.conf
+ local 'restored_block=object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ local json_output=/var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ local cleaned_block
++ sed '/^[[:space:]]*$/d'
+ cleaned_block='object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ -z object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0 ]]
+ [[ true == true ]]
+ message '[process_configs] Raw Block:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ -n [process_configs] Raw Block:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0 ]]
+ local 'message=[process_configs] Raw Block:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ print '[process_configs] Raw Block:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
+ [[ -n [process_configs] Raw Block:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0 ]]
+ echo -en '[process_configs] Raw Block:\nobject-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0'
[process_configs] Raw Block:
object-group network SOME-THING
  description Local Office Subnets
  network-object host 10.0.0.1
  network-object 192.168.12.0 255.255.255.0+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local object_line
++ head -n 1
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ object_line='object-group network SOME-THING'
+ [[ -z object-group network SOME-THING ]]
+ local object_keyword type_value
++ awk '{print $1}'
+ object_keyword=object-group
++ awk '{$1=""; print substr($0,2)}'
+ type_value='network SOME-THING'
+ [[ true == true ]]
+ print '[process_configs] object   : object-group'
+ [[ -n [process_configs] object   : object-group ]]
+ echo -en '[process_configs] object   : object-group'
[process_configs] object   : object-group+ print '[process_configs] type     : network SOME-THING'
+ [[ -n [process_configs] type     : network SOME-THING ]]
+ echo -en '[process_configs] type     : network SOME-THING'
[process_configs] type     : network SOME-THING+ entries=()
+ local -a entries
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='object-group network SOME-THING'
+ [[ -z object-group network SOME-THING ]]
+ [[ object-group network some-thing =~ ^description[[:space:]] ]]
+ entries+=("${trimmed}")
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='description Local Office Subnets'
+ [[ -z description Local Office Subnets ]]
+ [[ description local office subnets =~ ^description[[:space:]] ]]
+ continue
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='network-object host 10.0.0.1'
+ [[ -z network-object host 10.0.0.1 ]]
+ [[ network-object host 10.0.0.1 =~ ^description[[:space:]] ]]
+ entries+=("${trimmed}")
+ IFS=
+ read -r line
+ local trimmed
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ trimmed='network-object 192.168.12.0 255.255.255.0'
+ [[ -z network-object 192.168.12.0 255.255.255.0 ]]
+ [[ network-object 192.168.12.0 255.255.255.0 =~ ^description[[:space:]] ]]
+ entries+=("${trimmed}")
+ IFS=
+ read -r line
+ ((  3 > 1  ))
+ entries=("${entries[@]:1}")
+ [[ true == true ]]
+ message '[process_configs] Entries:'
+ [[ -n [process_configs] Entries: ]]
+ local 'message=[process_configs] Entries:'
+ print '[process_configs] Entries:'
+ [[ -n [process_configs] Entries: ]]
+ echo -en '[process_configs] Entries:'
[process_configs] Entries:+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ for e in "${entries[@]}"
+ print '  - network-object host 10.0.0.1'
+ [[ -n   - network-object host 10.0.0.1 ]]
+ echo -en '  - network-object host 10.0.0.1'
  - network-object host 10.0.0.1+ for e in "${entries[@]}"
+ print '  - network-object 192.168.12.0 255.255.255.0'
+ [[ -n   - network-object 192.168.12.0 255.255.255.0 ]]
+ echo -en '  - network-object 192.168.12.0 255.255.255.0'
  - network-object 192.168.12.0 255.255.255.0+ local matched_line
++ grep -wF 10.0.0.1
++ head -n 1
++ sed -E 's/^[[:space:]]*//;s/[[:space:]]*$//'
+ matched_line='network-object host 10.0.0.1'
+ [[ -z network-object host 10.0.0.1 ]]
+ [[ true == true ]]
+ message '[process_configs] Matched: network-object host 10.0.0.1'
+ [[ -n [process_configs] Matched: network-object host 10.0.0.1 ]]
+ local 'message=[process_configs] Matched: network-object host 10.0.0.1'
+ print '[process_configs] Matched: network-object host 10.0.0.1'
+ [[ -n [process_configs] Matched: network-object host 10.0.0.1 ]]
+ echo -en '[process_configs] Matched: network-object host 10.0.0.1'
[process_configs] Matched: network-object host 10.0.0.1+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local desc_val=false
+ [[ -z false ]]
+ [[ true == true ]]
+ message '[process_configs] Description: false'
+ [[ -n [process_configs] Description: false ]]
+ local 'message=[process_configs] Description: false'
+ print '[process_configs] Description: false'
+ [[ -n [process_configs] Description: false ]]
+ echo -en '[process_configs] Description: false'
[process_configs] Description: false+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ local group_val=Unclassified
+ [[ true == true ]]
+ local object_key
++ awk '{print $NF}'
++ sed -E 's/[[:punct:]]*$//'
+ object_key=SOME-THING
++ jq -r --arg key SOME-THING 'map(select(.match[]? | contains($key))) | .[0].group'
+ group_val='Identified Matching Entries'
+ [[ -z Identified Matching Entries ]]
+ [[ Identified Matching Entries == \n\u\l\l ]]
+ [[ -z Identified Matching Entries ]]
+ [[ Identified Matching Entries == \n\u\l\l ]]
+ [[ true == true ]]
+ message '[process_configs] Group: Identified Matching Entries'
+ [[ -n [process_configs] Group: Identified Matching Entries ]]
+ local 'message=[process_configs] Group: Identified Matching Entries'
+ print '[process_configs] Group: Identified Matching Entries'
+ [[ -n [process_configs] Group: Identified Matching Entries ]]
+ echo -en '[process_configs] Group: Identified Matching Entries'
[process_configs] Group: Identified Matching Entries+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
++ printf '%s\n' 'network-object host 10.0.0.1' 'network-object 192.168.12.0 255.255.255.0'
++ jq -R .
++ jq -s .
+ local 'entries_2json=[
  "network-object host 10.0.0.1",
  "network-object 192.168.12.0 255.255.255.0"
]'
+ export target_object
+ [[ 2 -eq 1 ]]
++ jq -n --arg object object-group --arg type 'network SOME-THING' --arg description false --argjson entries '[
  "network-object host 10.0.0.1",
  "network-object 192.168.12.0 255.255.255.0"
]' --arg group 'Identified Matching Entries' '{
                  object: $object,
                  type: $type,
                  description: ($description | select(. != "" and . != "null") // false),
                  entries: $entries,
                  group: $group
                }'
+ target_object='{
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
+ [[ -n /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json ]]
+ [[ -n {
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
} ]]
+ print '{
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
+ [[ -n {
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
} ]]
+ echo -en '{
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
+ [[ true == true ]]
+ message '[process_configs] JSON Object (output):'
+ [[ -n [process_configs] JSON Object (output): ]]
+ local 'message=[process_configs] JSON Object (output):'
+ print '[process_configs] JSON Object (output):'
+ [[ -n [process_configs] JSON Object (output): ]]
+ echo -en '[process_configs] JSON Object (output):'
[process_configs] JSON Object (output):+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ print '{
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
+ [[ -n {
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
+ jq .
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
} ]]
+ echo -en '{
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}'
{
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
}
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ return 0
+ [[ -s {
  "object": "object-group",
  "type": "network SOME-THING",
  "description": "false",
  "entries": [
    "network-object host 10.0.0.1",
    "network-object 192.168.12.0 255.255.255.0"
  ],
  "group": "Identified Matching Entries"
} ]]
+ return 0
+ export json_outfile=reports/json/10.0.0.1.json
+ json_outfile=reports/json/10.0.0.1.json
+ [[ -s /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json ]]
+ jq -s --arg target 10.0.0.1 '{ target: $target, configs: . }' /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk/fragments.json
+ [[ true == true ]]
+ jq . reports/json/10.0.0.1.json
{
  "target": "10.0.0.1",
  "configs": [
    {
      "object": "object-group",
      "type": "network BU1-NETWORK",
      "description": "false",
      "entries": [
        "network-object host 10.0.0.1",
        "network-object host 10.0.1.2",
        "network-object 192.168.1.0 255.255.255.0"
      ],
      "group": "Identified Matching Entries"
    },
    {
      "object": "access-list",
      "type": false,
      "description": "false",
      "entries": [
        "access-list OUTSIDE extended permit ip host 10.0.0.1 any"
      ],
      "group": "Unclassified"
    },
    {
      "object": "object-group",
      "type": "network SOME-THING",
      "description": "false",
      "entries": [
        "network-object host 10.0.0.1",
        "network-object 192.168.12.0 255.255.255.0"
      ],
      "group": "Identified Matching Entries"
    }
  ]
}
+ newline
+ local count=1
+ (( i = 0 ))
+ (( i < count ))
+ echo

+ (( i++ ))
+ (( i < count ))
+ return 0
+ unset verbose debug
+ [[ -d /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk ]]
+ rm -rf /var/folders/vp/4k9xy96d7zx8lhmgrr4khsj80000gn/T/tmp.NZIY81cYSk
